import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const background: Array<FractureRuleType> = [
  {selector: '.bg-gray-0', declarations: {backgroundColor: 'var(--gray-0)'}, hasHover: true },
  {selector: '.bg-gray-25', declarations: {backgroundColor: 'var(--gray-25)'}, hasHover: true },
  {selector: '.bg-gray-50', declarations: {backgroundColor: 'var(--gray-50)'}, hasHover: true },
  {selector: '.bg-gray-100', declarations: {backgroundColor: 'var(--gray-100)'}, hasHover: true },
  {selector: '.bg-gray-200', declarations: {backgroundColor: 'var(--gray-200)'}, hasHover: true },
  {selector: '.bg-gray-300', declarations: {backgroundColor: 'var(--gray-300)'}, hasHover: true },
  {selector: '.bg-gray-400', declarations: {backgroundColor: 'var(--gray-400)'}, hasHover: true },
  {selector: '.bg-gray-500', declarations: {backgroundColor: 'var(--gray-500)'}, hasHover: true },
  {selector: '.bg-gray-600', declarations: {backgroundColor: 'var(--gray-600)'}, hasHover: true },
  {selector: '.bg-gray-700', declarations: {backgroundColor: 'var(--gray-700)'}, hasHover: true },
  {selector: '.bg-gray-800', declarations: {backgroundColor: 'var(--gray-800)'}, hasHover: true },
  {selector: '.bg-gray-900', declarations: {backgroundColor: 'var(--gray-900)'}, hasHover: true },
  {selector: '.bg-gray-1000', declarations: {backgroundColor: 'var(--gray-1000)'}, hasHover: true },

  {selector: '.bg-red-100', declarations: {backgroundColor: 'var(--red-100)'}, hasHover: true },
  {selector: '.bg-red-200', declarations: {backgroundColor: 'var(--red-200)'}, hasHover: true },
  {selector: '.bg-red-300', declarations: {backgroundColor: 'var(--red-300)'}, hasHover: true },
  {selector: '.bg-red-400', declarations: {backgroundColor: 'var(--red-400)'}, hasHover: true },
  {selector: '.bg-red-500', declarations: {backgroundColor: 'var(--red-500)'}, hasHover: true },
  {selector: '.bg-red-600', declarations: {backgroundColor: 'var(--red-600)'}, hasHover: true },
  {selector: '.bg-red-700', declarations: {backgroundColor: 'var(--red-700)'}, hasHover: true },
  {selector: '.bg-red-800', declarations: {backgroundColor: 'var(--red-800)'}, hasHover: true },
  {selector: '.bg-red-900', declarations: {backgroundColor: 'var(--red-900)'}, hasHover: true },

  {selector: '.bg-green-100', declarations: {backgroundColor: 'var(--green-100)'}, hasHover: true },
  {selector: '.bg-green-200', declarations: {backgroundColor: 'var(--green-200)'}, hasHover: true },
  {selector: '.bg-green-300', declarations: {backgroundColor: 'var(--green-300)'}, hasHover: true },
  {selector: '.bg-green-400', declarations: {backgroundColor: 'var(--green-400)'}, hasHover: true },
  {selector: '.bg-green-500', declarations: {backgroundColor: 'var(--green-500)'}, hasHover: true },
  {selector: '.bg-green-600', declarations: {backgroundColor: 'var(--green-600)'}, hasHover: true },
  {selector: '.bg-green-700', declarations: {backgroundColor: 'var(--green-700)'}, hasHover: true },
  {selector: '.bg-green-800', declarations: {backgroundColor: 'var(--green-800)'}, hasHover: true },
  {selector: '.bg-green-900', declarations: {backgroundColor: 'var(--green-900)'}, hasHover: true },

  {selector: '.bg-blue-100', declarations: {backgroundColor: 'var(--blue-100)'}, hasHover: true },
  {selector: '.bg-blue-200', declarations: {backgroundColor: 'var(--blue-200)'}, hasHover: true },
  {selector: '.bg-blue-300', declarations: {backgroundColor: 'var(--blue-300)'}, hasHover: true },
  {selector: '.bg-blue-400', declarations: {backgroundColor: 'var(--blue-400)'}, hasHover: true },
  {selector: '.bg-blue-500', declarations: {backgroundColor: 'var(--blue-500)'}, hasHover: true },
  {selector: '.bg-blue-600', declarations: {backgroundColor: 'var(--blue-600)'}, hasHover: true },
  {selector: '.bg-blue-700', declarations: {backgroundColor: 'var(--blue-700)'}, hasHover: true },
  {selector: '.bg-blue-800', declarations: {backgroundColor: 'var(--blue-800)'}, hasHover: true },
  {selector: '.bg-blue-900', declarations: {backgroundColor: 'var(--blue-900)'}, hasHover: true },

  {selector: '.bg-yellow-100', declarations: {backgroundColor: 'var(--yellow-100)'}, hasHover: true },
  {selector: '.bg-yellow-200', declarations: {backgroundColor: 'var(--yellow-200)'}, hasHover: true },
  {selector: '.bg-yellow-300', declarations: {backgroundColor: 'var(--yellow-300)'}, hasHover: true },
  {selector: '.bg-yellow-400', declarations: {backgroundColor: 'var(--yellow-400)'}, hasHover: true },
  {selector: '.bg-yellow-500', declarations: {backgroundColor: 'var(--yellow-500)'}, hasHover: true },
  {selector: '.bg-yellow-600', declarations: {backgroundColor: 'var(--yellow-600)'}, hasHover: true },
  {selector: '.bg-yellow-700', declarations: {backgroundColor: 'var(--yellow-700)'}, hasHover: true },
  {selector: '.bg-yellow-800', declarations: {backgroundColor: 'var(--yellow-800)'}, hasHover: true },
  {selector: '.bg-yellow-900', declarations: {backgroundColor: 'var(--yellow-900)'}, hasHover: true },

  {selector: '.bg-purple-100', declarations: {backgroundColor: 'var(--purple-100)'}, hasHover: true },
  {selector: '.bg-purple-200', declarations: {backgroundColor: 'var(--purple-200)'}, hasHover: true },
  {selector: '.bg-purple-300', declarations: {backgroundColor: 'var(--purple-300)'}, hasHover: true },
  {selector: '.bg-purple-400', declarations: {backgroundColor: 'var(--purple-400)'}, hasHover: true },
  {selector: '.bg-purple-500', declarations: {backgroundColor: 'var(--purple-500)'}, hasHover: true },
  {selector: '.bg-purple-600', declarations: {backgroundColor: 'var(--purple-600)'}, hasHover: true },
  {selector: '.bg-purple-700', declarations: {backgroundColor: 'var(--purple-700)'}, hasHover: true },
  {selector: '.bg-purple-800', declarations: {backgroundColor: 'var(--purple-800)'}, hasHover: true },
  {selector: '.bg-purple-900', declarations: {backgroundColor: 'var(--purple-900)'}, hasHover: true },

  {selector: '.bg-pink-100', declarations: {backgroundColor: 'var(--pink-100)'}, hasHover: true },
  {selector: '.bg-pink-200', declarations: {backgroundColor: 'var(--pink-200)'}, hasHover: true },
  {selector: '.bg-pink-300', declarations: {backgroundColor: 'var(--pink-300)'}, hasHover: true },
  {selector: '.bg-pink-400', declarations: {backgroundColor: 'var(--pink-400)'}, hasHover: true },
  {selector: '.bg-pink-500', declarations: {backgroundColor: 'var(--pink-500)'}, hasHover: true },
  {selector: '.bg-pink-600', declarations: {backgroundColor: 'var(--pink-600)'}, hasHover: true },
  {selector: '.bg-pink-700', declarations: {backgroundColor: 'var(--pink-700)'}, hasHover: true },
  {selector: '.bg-pink-800', declarations: {backgroundColor: 'var(--pink-800)'}, hasHover: true },
  {selector: '.bg-pink-900', declarations: {backgroundColor: 'var(--pink-900)'}, hasHover: true },
];
