import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const background: Array<FractureRuleType> = [
  {selector: 'bg-gray-0', declarations: {backgroundColor: 'rgba(var(--rgb-gray-0), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1}},
  {selector: 'bg-gray-25', declarations: {backgroundColor: 'rgba(var(--rgb-gray-25), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-50', declarations: {backgroundColor: 'rgba(var(--rgb-gray-50), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-100', declarations: {backgroundColor: 'rgba(var(--rgb-gray-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-200', declarations: {backgroundColor: 'rgba(var(--rgb-gray-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-300', declarations: {backgroundColor: 'rgba(var(--rgb-gray-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-400', declarations: {backgroundColor: 'rgba(var(--rgb-gray-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-500', declarations: {backgroundColor: 'rgba(var(--rgb-gray-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-600', declarations: {backgroundColor: 'rgba(var(--rgb-gray-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-700', declarations: {backgroundColor: 'rgba(var(--rgb-gray-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-800', declarations: {backgroundColor: 'rgba(var(--rgb-gray-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-900', declarations: {backgroundColor: 'rgba(var(--rgb-gray-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-1000', declarations: {backgroundColor: 'rgba(var(--rgb-gray-1000), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-red-100', declarations: {backgroundColor: 'rgba(var(--rgb-red-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-200', declarations: {backgroundColor: 'rgba(var(--rgb-red-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-300', declarations: {backgroundColor: 'rgba(var(--rgb-red-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-400', declarations: {backgroundColor: 'rgba(var(--rgb-red-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-500', declarations: {backgroundColor: 'rgba(var(--rgb-red-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-600', declarations: {backgroundColor: 'rgba(var(--rgb-red-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-700', declarations: {backgroundColor: 'rgba(var(--rgb-red-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-800', declarations: {backgroundColor: 'rgba(var(--rgb-red-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-900', declarations: {backgroundColor: 'rgba(var(--rgb-red-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-green-100', declarations: {backgroundColor: 'rgba(var(--rgb-green-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-200', declarations: {backgroundColor: 'rgba(var(--rgb-green-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-300', declarations: {backgroundColor: 'rgba(var(--rgb-green-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-400', declarations: {backgroundColor: 'rgba(var(--rgb-green-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-500', declarations: {backgroundColor: 'rgba(var(--rgb-green-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-600', declarations: {backgroundColor: 'rgba(var(--rgb-green-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-700', declarations: {backgroundColor: 'rgba(var(--rgb-green-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-800', declarations: {backgroundColor: 'rgba(var(--rgb-green-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-900', declarations: {backgroundColor: 'rgba(var(--rgb-green-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-blue-100', declarations: {backgroundColor: 'rgba(var(--rgb-blue-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-200', declarations: {backgroundColor: 'rgba(var(--rgb-blue-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-300', declarations: {backgroundColor: 'rgba(var(--rgb-blue-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-400', declarations: {backgroundColor: 'rgba(var(--rgb-blue-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-500', declarations: {backgroundColor: 'rgba(var(--rgb-blue-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-600', declarations: {backgroundColor: 'rgba(var(--rgb-blue-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-700', declarations: {backgroundColor: 'rgba(var(--rgb-blue-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-800', declarations: {backgroundColor: 'rgba(var(--rgb-blue-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-900', declarations: {backgroundColor: 'rgba(var(--rgb-blue-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-yellow-100', declarations: {backgroundColor: 'rgba(var(--rgb-yellow-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-200', declarations: {backgroundColor: 'rgba(var(--rgb-yellow-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-300', declarations: {backgroundColor: 'rgba(var(--rgb-yellow-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-400', declarations: {backgroundColor: 'rgba(var(--rgb-yellow-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-500', declarations: {backgroundColor: 'rgba(var(--rgb-yellow-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-600', declarations: {backgroundColor: 'rgba(var(--rgb-yellow-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-700', declarations: {backgroundColor: 'rgba(var(--rgb-yellow-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-800', declarations: {backgroundColor: 'rgba(var(--rgb-yellow-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-900', declarations: {backgroundColor: 'rgba(var(--rgb-yellow-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-purple-100', declarations: {backgroundColor: 'rgba(var(--rgb-purple-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-200', declarations: {backgroundColor: 'rgba(var(--rgb-purple-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-300', declarations: {backgroundColor: 'rgba(var(--rgb-purple-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-400', declarations: {backgroundColor: 'rgba(var(--rgb-purple-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-500', declarations: {backgroundColor: 'rgba(var(--rgb-purple-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-600', declarations: {backgroundColor: 'rgba(var(--rgb-purple-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-700', declarations: {backgroundColor: 'rgba(var(--rgb-purple-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-800', declarations: {backgroundColor: 'rgba(var(--rgb-purple-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-900', declarations: {backgroundColor: 'rgba(var(--rgb-purple-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-pink-100', declarations: {backgroundColor: 'rgba(var(--rgb-pink-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-200', declarations: {backgroundColor: 'rgba(var(--rgb-pink-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-300', declarations: {backgroundColor: 'rgba(var(--rgb-pink-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-400', declarations: {backgroundColor: 'rgba(var(--rgb-pink-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-500', declarations: {backgroundColor: 'rgba(var(--rgb-pink-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-600', declarations: {backgroundColor: 'rgba(var(--rgb-pink-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-700', declarations: {backgroundColor: 'rgba(var(--rgb-pink-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-800', declarations: {backgroundColor: 'rgba(var(--rgb-pink-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-900', declarations: {backgroundColor: 'rgba(var(--rgb-pink-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
];
