import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const background: Array<FractureRuleType> = [
  {selector: 'bg-gray-0', declarations: {backgroundColor: 'rgba(var(--rgba--gray-0), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1}},
  {selector: 'bg-gray-25', declarations: {backgroundColor: 'rgba(var(--rgba--gray-25), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-50', declarations: {backgroundColor: 'rgba(var(--rgba--gray-50), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-100', declarations: {backgroundColor: 'rgba(var(--rgba--gray-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-200', declarations: {backgroundColor: 'rgba(var(--rgba--gray-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-300', declarations: {backgroundColor: 'rgba(var(--rgba--gray-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-400', declarations: {backgroundColor: 'rgba(var(--rgba--gray-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-500', declarations: {backgroundColor: 'rgba(var(--rgba--gray-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-600', declarations: {backgroundColor: 'rgba(var(--rgba--gray-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-700', declarations: {backgroundColor: 'rgba(var(--rgba--gray-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-800', declarations: {backgroundColor: 'rgba(var(--rgba--gray-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-900', declarations: {backgroundColor: 'rgba(var(--rgba--gray-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-gray-1000', declarations: {backgroundColor: 'rgba(var(--rgba--gray-1000), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-red-100', declarations: {backgroundColor: 'rgba(var(--rgba--red-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-200', declarations: {backgroundColor: 'rgba(var(--rgba--red-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-300', declarations: {backgroundColor: 'rgba(var(--rgba--red-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-400', declarations: {backgroundColor: 'rgba(var(--rgba--red-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-500', declarations: {backgroundColor: 'rgba(var(--rgba--red-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-600', declarations: {backgroundColor: 'rgba(var(--rgba--red-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-700', declarations: {backgroundColor: 'rgba(var(--rgba--red-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-800', declarations: {backgroundColor: 'rgba(var(--rgba--red-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-red-900', declarations: {backgroundColor: 'rgba(var(--rgba--red-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-green-100', declarations: {backgroundColor: 'rgba(var(--rgba--green-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-200', declarations: {backgroundColor: 'rgba(var(--rgba--green-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-300', declarations: {backgroundColor: 'rgba(var(--rgba--green-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-400', declarations: {backgroundColor: 'rgba(var(--rgba--green-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-500', declarations: {backgroundColor: 'rgba(var(--rgba--green-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-600', declarations: {backgroundColor: 'rgba(var(--rgba--green-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-700', declarations: {backgroundColor: 'rgba(var(--rgba--green-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-800', declarations: {backgroundColor: 'rgba(var(--rgba--green-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-green-900', declarations: {backgroundColor: 'rgba(var(--rgba--green-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-blue-100', declarations: {backgroundColor: 'rgba(var(--rgba--blue-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-200', declarations: {backgroundColor: 'rgba(var(--rgba--blue-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-300', declarations: {backgroundColor: 'rgba(var(--rgba--blue-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-400', declarations: {backgroundColor: 'rgba(var(--rgba--blue-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-500', declarations: {backgroundColor: 'rgba(var(--rgba--blue-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-600', declarations: {backgroundColor: 'rgba(var(--rgba--blue-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-700', declarations: {backgroundColor: 'rgba(var(--rgba--blue-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-800', declarations: {backgroundColor: 'rgba(var(--rgba--blue-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-blue-900', declarations: {backgroundColor: 'rgba(var(--rgba--blue-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-yellow-100', declarations: {backgroundColor: 'rgba(var(--rgba--yellow-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-200', declarations: {backgroundColor: 'rgba(var(--rgba--yellow-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-300', declarations: {backgroundColor: 'rgba(var(--rgba--yellow-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-400', declarations: {backgroundColor: 'rgba(var(--rgba--yellow-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-500', declarations: {backgroundColor: 'rgba(var(--rgba--yellow-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-600', declarations: {backgroundColor: 'rgba(var(--rgba--yellow-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-700', declarations: {backgroundColor: 'rgba(var(--rgba--yellow-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-800', declarations: {backgroundColor: 'rgba(var(--rgba--yellow-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-yellow-900', declarations: {backgroundColor: 'rgba(var(--rgba--yellow-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-purple-100', declarations: {backgroundColor: 'rgba(var(--rgba--purple-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-200', declarations: {backgroundColor: 'rgba(var(--rgba--purple-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-300', declarations: {backgroundColor: 'rgba(var(--rgba--purple-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-400', declarations: {backgroundColor: 'rgba(var(--rgba--purple-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-500', declarations: {backgroundColor: 'rgba(var(--rgba--purple-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-600', declarations: {backgroundColor: 'rgba(var(--rgba--purple-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-700', declarations: {backgroundColor: 'rgba(var(--rgba--purple-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-800', declarations: {backgroundColor: 'rgba(var(--rgba--purple-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-purple-900', declarations: {backgroundColor: 'rgba(var(--rgba--purple-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },

  {selector: 'bg-pink-100', declarations: {backgroundColor: 'rgba(var(--rgba--pink-100), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-200', declarations: {backgroundColor: 'rgba(var(--rgba--pink-200), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-300', declarations: {backgroundColor: 'rgba(var(--rgba--pink-300), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-400', declarations: {backgroundColor: 'rgba(var(--rgba--pink-400), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-500', declarations: {backgroundColor: 'rgba(var(--rgba--pink-500), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-600', declarations: {backgroundColor: 'rgba(var(--rgba--pink-600), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-700', declarations: {backgroundColor: 'rgba(var(--rgba--pink-700), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-800', declarations: {backgroundColor: 'rgba(var(--rgba--pink-800), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
  {selector: 'bg-pink-900', declarations: {backgroundColor: 'rgba(var(--rgba--pink-900), var(--background-opacity))'}, hasHover: true, variables: {'--background-opacity': 1} },
];
