import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const color: Array<FractureRuleType> = [
  {selector: 'gray-0', declarations: {color: 'rgba(var(--rgb-gray-0), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-25', declarations: {color: 'rgba(var(--rgb-gray-25), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-50', declarations: {color: 'rgba(var(--rgb-gray-50), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-100', declarations: {color: 'rgba(var(--rgb-gray-100), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-200', declarations: {color: 'rgba(var(--rgb-gray-200), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-300', declarations: {color: 'rgba(var(--rgb-gray-300), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-400', declarations: {color: 'rgba(var(--rgb-gray-400), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-500', declarations: {color: 'rgba(var(--rgb-gray-500), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-600', declarations: {color: 'rgba(var(--rgb-gray-600), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-700', declarations: {color: 'rgba(var(--rgb-gray-700), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-800', declarations: {color: 'rgba(var(--rgb-gray-800), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-900', declarations: {color: 'rgba(var(--rgb-gray-900), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'gray-1000', declarations: {color: 'rgba(var(--rgb-gray-1000), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },

  {selector: 'red-100', declarations: {color: 'rgba(var(--rgb-red-100), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'red-200', declarations: {color: 'rgba(var(--rgb-red-200), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'red-300', declarations: {color: 'rgba(var(--rgb-red-300), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'red-400', declarations: {color: 'rgba(var(--rgb-red-400), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'red-500', declarations: {color: 'rgba(var(--rgb-red-500), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'red-600', declarations: {color: 'rgba(var(--rgb-red-600), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'red-700', declarations: {color: 'rgba(var(--rgb-red-700), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'red-800', declarations: {color: 'rgba(var(--rgb-red-800), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'red-900', declarations: {color: 'rgba(var(--rgb-red-900), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },

  {selector: 'green-100', declarations: {color: 'rgba(var(--rgb-green-100), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'green-200', declarations: {color: 'rgba(var(--rgb-green-200), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'green-300', declarations: {color: 'rgba(var(--rgb-green-300), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'green-400', declarations: {color: 'rgba(var(--rgb-green-400), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'green-500', declarations: {color: 'rgba(var(--rgb-green-500), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'green-600', declarations: {color: 'rgba(var(--rgb-green-600), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'green-700', declarations: {color: 'rgba(var(--rgb-green-700), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'green-800', declarations: {color: 'rgba(var(--rgb-green-800), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'green-900', declarations: {color: 'rgba(var(--rgb-green-900), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },

  {selector: 'blue-100', declarations: {color: 'rgba(var(--rgb-blue-100), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'blue-200', declarations: {color: 'rgba(var(--rgb-blue-200), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'blue-300', declarations: {color: 'rgba(var(--rgb-blue-300), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'blue-400', declarations: {color: 'rgba(var(--rgb-blue-400), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'blue-500', declarations: {color: 'rgba(var(--rgb-blue-500), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'blue-600', declarations: {color: 'rgba(var(--rgb-blue-600), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'blue-700', declarations: {color: 'rgba(var(--rgb-blue-700), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'blue-800', declarations: {color: 'rgba(var(--rgb-blue-800), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'blue-900', declarations: {color: 'rgba(var(--rgb-blue-900), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },

  {selector: 'yellow-100', declarations: {color: 'rgba(var(--rgb-yellow-100), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'yellow-200', declarations: {color: 'rgba(var(--rgb-yellow-200), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'yellow-300', declarations: {color: 'rgba(var(--rgb-yellow-300), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'yellow-400', declarations: {color: 'rgba(var(--rgb-yellow-400), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'yellow-500', declarations: {color: 'rgba(var(--rgb-yellow-500), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'yellow-600', declarations: {color: 'rgba(var(--rgb-yellow-600), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'yellow-700', declarations: {color: 'rgba(var(--rgb-yellow-700), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'yellow-800', declarations: {color: 'rgba(var(--rgb-yellow-800), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'yellow-900', declarations: {color: 'rgba(var(--rgb-yellow-900), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },

  {selector: 'purple-100', declarations: {color: 'rgba(var(--rgb-purple-100), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'purple-200', declarations: {color: 'rgba(var(--rgb-purple-200), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'purple-300', declarations: {color: 'rgba(var(--rgb-purple-300), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'purple-400', declarations: {color: 'rgba(var(--rgb-purple-400), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'purple-500', declarations: {color: 'rgba(var(--rgb-purple-500), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'purple-600', declarations: {color: 'rgba(var(--rgb-purple-600), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'purple-700', declarations: {color: 'rgba(var(--rgb-purple-700), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'purple-800', declarations: {color: 'rgba(var(--rgb-purple-800), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'purple-900', declarations: {color: 'rgba(var(--rgb-purple-900), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },

  {selector: 'pink-100', declarations: {color: 'rgba(var(--rgb-pink-100), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'pink-200', declarations: {color: 'rgba(var(--rgb-pink-200), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'pink-300', declarations: {color: 'rgba(var(--rgb-pink-300), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'pink-400', declarations: {color: 'rgba(var(--rgb-pink-400), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'pink-500', declarations: {color: 'rgba(var(--rgb-pink-500), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'pink-600', declarations: {color: 'rgba(var(--rgb-pink-600), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'pink-700', declarations: {color: 'rgba(var(--rgb-pink-700), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'pink-800', declarations: {color: 'rgba(var(--rgb-pink-800), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
  {selector: 'pink-900', declarations: {color: 'rgba(var(--rgb-pink-900), var(--color-opacity))'}, hasHover: true, variables: {'--color-opacity': 1} },
];
