import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const color: Array<FractureRuleType> = [
  {selector: '.gray-0', declarations: {color: 'var(--gray-0)'}, hasHover: true },
  {selector: '.gray-25', declarations: {color: 'var(--gray-25)'}, hasHover: true },
  {selector: '.gray-50', declarations: {color: 'var(--gray-50)'}, hasHover: true },
  {selector: '.gray-100', declarations: {color: 'var(--gray-100)'}, hasHover: true },
  {selector: '.gray-200', declarations: {color: 'var(--gray-200)'}, hasHover: true },
  {selector: '.gray-300', declarations: {color: 'var(--gray-300)'}, hasHover: true },
  {selector: '.gray-400', declarations: {color: 'var(--gray-400)'}, hasHover: true },
  {selector: '.gray-500', declarations: {color: 'var(--gray-500)'}, hasHover: true },
  {selector: '.gray-600', declarations: {color: 'var(--gray-600)'}, hasHover: true },
  {selector: '.gray-700', declarations: {color: 'var(--gray-700)'}, hasHover: true },
  {selector: '.gray-800', declarations: {color: 'var(--gray-800)'}, hasHover: true },
  {selector: '.gray-900', declarations: {color: 'var(--gray-900)'}, hasHover: true },
  {selector: '.gray-1000', declarations: {color: 'var(--gray-1000)'}, hasHover: true },

  {selector: '.red-100', declarations: {color: 'var(--red-100)'}, hasHover: true },
  {selector: '.red-200', declarations: {color: 'var(--red-200)'}, hasHover: true },
  {selector: '.red-300', declarations: {color: 'var(--red-300)'}, hasHover: true },
  {selector: '.red-400', declarations: {color: 'var(--red-400)'}, hasHover: true },
  {selector: '.red-500', declarations: {color: 'var(--red-500)'}, hasHover: true },
  {selector: '.red-600', declarations: {color: 'var(--red-600)'}, hasHover: true },
  {selector: '.red-700', declarations: {color: 'var(--red-700)'}, hasHover: true },
  {selector: '.red-800', declarations: {color: 'var(--red-800)'}, hasHover: true },
  {selector: '.red-900', declarations: {color: 'var(--red-900)'}, hasHover: true },

  {selector: '.green-100', declarations: {color: 'var(--green-100)'}, hasHover: true },
  {selector: '.green-200', declarations: {color: 'var(--green-200)'}, hasHover: true },
  {selector: '.green-300', declarations: {color: 'var(--green-300)'}, hasHover: true },
  {selector: '.green-400', declarations: {color: 'var(--green-400)'}, hasHover: true },
  {selector: '.green-500', declarations: {color: 'var(--green-500)'}, hasHover: true },
  {selector: '.green-600', declarations: {color: 'var(--green-600)'}, hasHover: true },
  {selector: '.green-700', declarations: {color: 'var(--green-700)'}, hasHover: true },
  {selector: '.green-800', declarations: {color: 'var(--green-800)'}, hasHover: true },
  {selector: '.green-900', declarations: {color: 'var(--green-900)'}, hasHover: true },

  {selector: '.blue-100', declarations: {color: 'var(--blue-100)'}, hasHover: true },
  {selector: '.blue-200', declarations: {color: 'var(--blue-200)'}, hasHover: true },
  {selector: '.blue-300', declarations: {color: 'var(--blue-300)'}, hasHover: true },
  {selector: '.blue-400', declarations: {color: 'var(--blue-400)'}, hasHover: true },
  {selector: '.blue-500', declarations: {color: 'var(--blue-500)'}, hasHover: true },
  {selector: '.blue-600', declarations: {color: 'var(--blue-600)'}, hasHover: true },
  {selector: '.blue-700', declarations: {color: 'var(--blue-700)'}, hasHover: true },
  {selector: '.blue-800', declarations: {color: 'var(--blue-800)'}, hasHover: true },
  {selector: '.blue-900', declarations: {color: 'var(--blue-900)'}, hasHover: true },

  {selector: '.yellow-100', declarations: {color: 'var(--yellow-100)'}, hasHover: true },
  {selector: '.yellow-200', declarations: {color: 'var(--yellow-200)'}, hasHover: true },
  {selector: '.yellow-300', declarations: {color: 'var(--yellow-300)'}, hasHover: true },
  {selector: '.yellow-400', declarations: {color: 'var(--yellow-400)'}, hasHover: true },
  {selector: '.yellow-500', declarations: {color: 'var(--yellow-500)'}, hasHover: true },
  {selector: '.yellow-600', declarations: {color: 'var(--yellow-600)'}, hasHover: true },
  {selector: '.yellow-700', declarations: {color: 'var(--yellow-700)'}, hasHover: true },
  {selector: '.yellow-800', declarations: {color: 'var(--yellow-800)'}, hasHover: true },
  {selector: '.yellow-900', declarations: {color: 'var(--yellow-900)'}, hasHover: true },

  {selector: '.purple-100', declarations: {color: 'var(--purple-100)'}, hasHover: true },
  {selector: '.purple-200', declarations: {color: 'var(--purple-200)'}, hasHover: true },
  {selector: '.purple-300', declarations: {color: 'var(--purple-300)'}, hasHover: true },
  {selector: '.purple-400', declarations: {color: 'var(--purple-400)'}, hasHover: true },
  {selector: '.purple-500', declarations: {color: 'var(--purple-500)'}, hasHover: true },
  {selector: '.purple-600', declarations: {color: 'var(--purple-600)'}, hasHover: true },
  {selector: '.purple-700', declarations: {color: 'var(--purple-700)'}, hasHover: true },
  {selector: '.purple-800', declarations: {color: 'var(--purple-800)'}, hasHover: true },
  {selector: '.purple-900', declarations: {color: 'var(--purple-900)'}, hasHover: true },

  {selector: '.pink-100', declarations: {color: 'var(--pink-100)'}, hasHover: true },
  {selector: '.pink-200', declarations: {color: 'var(--pink-200)'}, hasHover: true },
  {selector: '.pink-300', declarations: {color: 'var(--pink-300)'}, hasHover: true },
  {selector: '.pink-400', declarations: {color: 'var(--pink-400)'}, hasHover: true },
  {selector: '.pink-500', declarations: {color: 'var(--pink-500)'}, hasHover: true },
  {selector: '.pink-600', declarations: {color: 'var(--pink-600)'}, hasHover: true },
  {selector: '.pink-700', declarations: {color: 'var(--pink-700)'}, hasHover: true },
  {selector: '.pink-800', declarations: {color: 'var(--pink-800)'}, hasHover: true },
  {selector: '.pink-900', declarations: {color: 'var(--pink-900)'}, hasHover: true },
];
