import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const color: Array<FractureRuleType> = [
  {selector: 'gray-0', property: 'color', value: 'var(--gray-0)', hasHover: true },
  {selector: 'gray-25', property: 'color', value: 'var(--gray-25)', hasHover: true },
  {selector: 'gray-50', property: 'color', value: 'var(--gray-50)', hasHover: true },
  {selector: 'gray-100', property: 'color', value: 'var(--gray-100)', hasHover: true },
  {selector: 'gray-200', property: 'color', value: 'var(--gray-200)', hasHover: true },
  {selector: 'gray-300', property: 'color', value: 'var(--gray-300)', hasHover: true },
  {selector: 'gray-400', property: 'color', value: 'var(--gray-400)', hasHover: true },
  {selector: 'gray-500', property: 'color', value: 'var(--gray-500)', hasHover: true },
  {selector: 'gray-600', property: 'color', value: 'var(--gray-600)', hasHover: true },
  {selector: 'gray-700', property: 'color', value: 'var(--gray-700)', hasHover: true },
  {selector: 'gray-800', property: 'color', value: 'var(--gray-800)', hasHover: true },
  {selector: 'gray-900', property: 'color', value: 'var(--gray-900)', hasHover: true },
  {selector: 'gray-1000', property: 'color', value: 'var(--gray-1000)', hasHover: true },

  {selector: 'red-100', property: 'color', value: 'var(--red-100)', hasHover: true },
  {selector: 'red-200', property: 'color', value: 'var(--red-200)', hasHover: true },
  {selector: 'red-300', property: 'color', value: 'var(--red-300)', hasHover: true },
  {selector: 'red-400', property: 'color', value: 'var(--red-400)', hasHover: true },
  {selector: 'red-500', property: 'color', value: 'var(--red-500)', hasHover: true },
  {selector: 'red-600', property: 'color', value: 'var(--red-600)', hasHover: true },
  {selector: 'red-700', property: 'color', value: 'var(--red-700)', hasHover: true },
  {selector: 'red-800', property: 'color', value: 'var(--red-800)', hasHover: true },
  {selector: 'red-900', property: 'color', value: 'var(--red-900)', hasHover: true },

  {selector: 'green-100', property: 'color', value: 'var(--green-100)', hasHover: true },
  {selector: 'green-200', property: 'color', value: 'var(--green-200)', hasHover: true },
  {selector: 'green-300', property: 'color', value: 'var(--green-300)', hasHover: true },
  {selector: 'green-400', property: 'color', value: 'var(--green-400)', hasHover: true },
  {selector: 'green-500', property: 'color', value: 'var(--green-500)', hasHover: true },
  {selector: 'green-600', property: 'color', value: 'var(--green-600)', hasHover: true },
  {selector: 'green-700', property: 'color', value: 'var(--green-700)', hasHover: true },
  {selector: 'green-800', property: 'color', value: 'var(--green-800)', hasHover: true },
  {selector: 'green-900', property: 'color', value: 'var(--green-900)', hasHover: true },

  {selector: 'blue-100', property: 'color', value: 'var(--blue-100)', hasHover: true },
  {selector: 'blue-200', property: 'color', value: 'var(--blue-200)', hasHover: true },
  {selector: 'blue-300', property: 'color', value: 'var(--blue-300)', hasHover: true },
  {selector: 'blue-400', property: 'color', value: 'var(--blue-400)', hasHover: true },
  {selector: 'blue-500', property: 'color', value: 'var(--blue-500)', hasHover: true },
  {selector: 'blue-600', property: 'color', value: 'var(--blue-600)', hasHover: true },
  {selector: 'blue-700', property: 'color', value: 'var(--blue-700)', hasHover: true },
  {selector: 'blue-800', property: 'color', value: 'var(--blue-800)', hasHover: true },
  {selector: 'blue-900', property: 'color', value: 'var(--blue-900)', hasHover: true },

  {selector: 'yellow-100', property: 'color', value: 'var(--yellow-100)', hasHover: true },
  {selector: 'yellow-200', property: 'color', value: 'var(--yellow-200)', hasHover: true },
  {selector: 'yellow-300', property: 'color', value: 'var(--yellow-300)', hasHover: true },
  {selector: 'yellow-400', property: 'color', value: 'var(--yellow-400)', hasHover: true },
  {selector: 'yellow-500', property: 'color', value: 'var(--yellow-500)', hasHover: true },
  {selector: 'yellow-600', property: 'color', value: 'var(--yellow-600)', hasHover: true },
  {selector: 'yellow-700', property: 'color', value: 'var(--yellow-700)', hasHover: true },
  {selector: 'yellow-800', property: 'color', value: 'var(--yellow-800)', hasHover: true },
  {selector: 'yellow-900', property: 'color', value: 'var(--yellow-900)', hasHover: true },

  {selector: 'purple-100', property: 'color', value: 'var(--purple-100)', hasHover: true },
  {selector: 'purple-200', property: 'color', value: 'var(--purple-200)', hasHover: true },
  {selector: 'purple-300', property: 'color', value: 'var(--purple-300)', hasHover: true },
  {selector: 'purple-400', property: 'color', value: 'var(--purple-400)', hasHover: true },
  {selector: 'purple-500', property: 'color', value: 'var(--purple-500)', hasHover: true },
  {selector: 'purple-600', property: 'color', value: 'var(--purple-600)', hasHover: true },
  {selector: 'purple-700', property: 'color', value: 'var(--purple-700)', hasHover: true },
  {selector: 'purple-800', property: 'color', value: 'var(--purple-800)', hasHover: true },
  {selector: 'purple-900', property: 'color', value: 'var(--purple-900)', hasHover: true },

  {selector: 'pink-100', property: 'color', value: 'var(--pink-100)', hasHover: true },
  {selector: 'pink-200', property: 'color', value: 'var(--pink-200)', hasHover: true },
  {selector: 'pink-300', property: 'color', value: 'var(--pink-300)', hasHover: true },
  {selector: 'pink-400', property: 'color', value: 'var(--pink-400)', hasHover: true },
  {selector: 'pink-500', property: 'color', value: 'var(--pink-500)', hasHover: true },
  {selector: 'pink-600', property: 'color', value: 'var(--pink-600)', hasHover: true },
  {selector: 'pink-700', property: 'color', value: 'var(--pink-700)', hasHover: true },
  {selector: 'pink-800', property: 'color', value: 'var(--pink-800)', hasHover: true },
  {selector: 'pink-900', property: 'color', value: 'var(--pink-900)', hasHover: true },
];
