import type { FractureRuleType } from "../../types/css-rules";

export const cursor: Array<FractureRuleType> = [
  { selector: 'no-events', declarations: { pointerEvents: 'none' } },
  { selector: 'cursor-alias', declarations: { cursor: 'alias' } },
  { selector: 'cursor-all-scroll', declarations: { cursor: 'all-scroll' } },
  { selector: 'cursor-auto', declarations: { cursor: 'auto' } },
  { selector: 'cursor-cell', declarations: { cursor: 'cell' } },
  { selector: 'cursor-context-menu', declarations: { cursor: 'context-menu' } },
  { selector: 'cursor-col-resize', declarations: { cursor: 'col-resize' } },
  { selector: 'cursor-copy', declarations: { cursor: 'copy' } },
  { selector: 'cursor-crosshair', declarations: { cursor: 'crosshair' } },
  { selector: 'cursor-default', declarations: { cursor: 'default' } },
  { selector: 'cursor-e-resize', declarations: { cursor: 'e-resize' } },
  { selector: 'cursor-ew-resize', declarations: { cursor: 'ew-resize' } },
  { selector: 'cursor-grab', declarations: { cursor: 'grab' } },
  { selector: 'cursor-grabbing', declarations: { cursor: 'grabbing' } },
  { selector: 'cursor-help', declarations: { cursor: 'help' } },
  { selector: 'cursor-move', declarations: { cursor: 'move' } },
  { selector: 'cursor-n-resize', declarations: { cursor: 'n-resize' } },
  { selector: 'cursor-ne-resize', declarations: { cursor: 'ne-resize' } },
  { selector: 'cursor-nesw-resize', declarations: { cursor: 'nesw-resize' } },
  { selector: 'cursor-ns-resize', declarations: { cursor: 'ns-resize' } },
  { selector: 'cursor-nw-resize', declarations: { cursor: 'nw-resize' } },
  { selector: 'cursor-nwse-resize', declarations: { cursor: 'nwse-resize' } },
  { selector: 'cursor-no-drop', declarations: { cursor: 'no-drop' } },
  { selector: 'cursor-none', declarations: { cursor: 'none' } },
  { selector: 'cursor-not-allowed', declarations: { cursor: 'not-allowed' } },
  { selector: 'cursor-pointer', declarations: { cursor: 'pointer' } },
  { selector: 'cursor-progress', declarations: { cursor: 'progress' } },
  { selector: 'cursor-row-resize', declarations: { cursor: 'row-resize' } },
  { selector: 'cursor-s-resize', declarations: { cursor: 's-resize' } },
  { selector: 'cursor-se-resize', declarations: { cursor: 'se-resize' } },
  { selector: 'cursor-sw-resize', declarations: { cursor: 'sw-resize' } },
  { selector: 'cursor-text', declarations: { cursor: 'text' } },
  { selector: 'cursor-w-resize', declarations: { cursor: 'w-resize' } },
  { selector: 'cursor-wait', declarations: { cursor: 'wait' } },
  { selector: 'cursor-zoom-in', declarations: { cursor: 'zoom-in' } },
  { selector: 'cursor-zoom-out', declarations: { cursor: 'zoom-out' } },
];
