import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const cursor: Array<FractureRuleType> = [
	{ selector: 'no-events', declarations:{ pointerEvents: 'none'} , hasHover: true },
  { selector: 'cursor-alias', declarations: {cursor: 'alias'}, hasHover: true },
  { selector: 'cursor-all-scroll', declarations: {cursor: 'all-scroll'} , hasHover: true },
  { selector: 'cursor-auto', declarations: {cursor: 'auto'}, hasHover: true },
  { selector: 'cursor-cell', declarations: {cursor: 'cell'}, hasHover: true },
  { selector: 'cursor-context-menu', declarations: {cursor: 'context-menu'}, hasHover: true },
  { selector: 'cursor-col-resize', declarations: {cursor: 'col-resize'}, hasHover: true },
  { selector: 'cursor-copy', declarations: {cursor: 'copy'}, hasHover: true },
  { selector: 'cursor-crosshair', declarations: {cursor: 'crosshair'}, hasHover: true },
  { selector: 'cursor-default', declarations: {cursor: 'default'}, hasHover: true },
  { selector: 'cursor-e-resize', declarations: {cursor: 'e-resize'}, hasHover: true },
  { selector: 'cursor-ew-resize', declarations: {cursor: 'ew-resize'}, hasHover: true },
  { selector: 'cursor-grab', declarations: {cursor: 'grab'}, hasHover: true },
  { selector: 'cursor-grabbing', declarations: {cursor: 'grabbing'}, hasHover: true },
  { selector: 'cursor-help', declarations: {cursor: 'help'}, hasHover: true },
  { selector: 'cursor-move', declarations: {cursor: 'move'}, hasHover: true },
  { selector: 'cursor-n-resize', declarations: {cursor: 'n-resize'}, hasHover: true },
  { selector: 'cursor-ne-resize', declarations: {cursor: 'ne-resize'}, hasHover: true },
  { selector: 'cursor-nesw-resize', declarations: {cursor: 'nesw-resize'}, hasHover: true },
  { selector: 'cursor-ns-resize', declarations: {cursor: 'ns-resize'}, hasHover: true },
  { selector: 'cursor-nw-resize', declarations: {cursor: 'nw-resize'}, hasHover: true },
  { selector: 'cursor-nwse-resize', declarations: {cursor: 'nwse-resize'}, hasHover: true },
  { selector: 'cursor-no-drop', declarations: {cursor: 'no-drop'}, hasHover: true },
  { selector: 'cursor-none', declarations: {cursor: 'none'}, hasHover: true },
  { selector: 'cursor-not-allowed', declarations: {cursor: 'not-allowed'}, hasHover: true },
  { selector: 'cursor-pointer', declarations: {cursor: 'pointer'}, hasHover: true },
  { selector: 'cursor-progress', declarations: {cursor: 'progress'}, hasHover: true },
  { selector: 'cursor-row-resize', declarations: {cursor: 'row-resize'}, hasHover: true },
  { selector: 'cursor-s-resize', declarations: {cursor: 's-resize'}, hasHover: true },
  { selector: 'cursor-se-resize', declarations: {cursor: 'se-resize'}, hasHover: true },
  { selector: 'cursor-sw-resize', declarations: {cursor: 'sw-resize'}, hasHover: true },
  { selector: 'cursor-text', declarations: {cursor: 'text'}, hasHover: true },
  { selector: 'cursor-w-resize', declarations: {cursor: 'w-resize'}, hasHover: true },
  { selector: 'cursor-wait', declarations: {cursor: 'wait'}, hasHover: true },
  { selector: 'cursor-zoom-in', declarations: {cursor: 'zoom-in'}, hasHover: true },
  { selector: 'cursor-zoom-out', declarations: {cursor: 'zoom-out'}, hasHover: true },
];
