import type { FractureRuleType } from "../../types/css-rules";

export const display: Array<FractureRuleType> = [
  { selector: "block", declarations: { display: "block" }, hasBreakpoints: true, },
  { selector: "contents", declarations: { display: "contents" }, hasBreakpoints: true },
  { selector: "flex", declarations: { display: "flex" }, hasBreakpoints: true },
  { selector: "flow-root", declarations: { display: "flow-root" }, hasBreakpoints: true },
  { selector: "grid", declarations: { display: "grid" }, hasBreakpoints: true },
  { selector: "inline", declarations: { display: "inline" }, hasBreakpoints: true },
  { selector: "inline-block", declarations: { display: "inline-block" }, hasBreakpoints: true },
  { selector: "inline-flex", declarations: { display: "inline-flex" }, hasBreakpoints: true },
  { selector: "inline-grid", declarations: { display: "inline-grid" }, hasBreakpoints: true },
  { selector: "inline-table", declarations: { display: "inline-table" }, hasBreakpoints: true },
  { selector: "list-item", declarations: { display: "list-item" } },
  { selector: "none", declarations: { display: "none" }, hasBreakpoints: true },
  { selector: "run-in", declarations: { display: "run-in" } },
  { selector: "table", declarations: { display: "table" } },
  { selector: "table-caption", declarations: { display: "table-caption" } },
  { selector: "table-cell", declarations: { display: "table-cell" } },
  { selector: "table-column", declarations: { display: "table-column" } },
  { selector: "table-column-group", declarations: { display: "table-column-group" } },
  { selector: "table-footer-group", declarations: { display: "table-footer-group" } },
  { selector: "table-header-group", declarations: { display: "table-header-group" } },
  { selector: "table-row", declarations: { display: "table-row" } },
  { selector: "table-row-group", declarations: { display: "table-row-group" } },
  { selector: "table-layout-fixed", declarations: { tableLayout: "fixed" } },
  { selector: "float-left", declarations: { float: "left" } },
  { selector: "float-right", declarations: { float: "right" } },
];
