import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const display: Array<FractureRuleType> = [
	{ selector: ".block", declarations: {display: "block"}, hasBreakpoints: true },
	{ selector: ".contents", declarations: {display: "contents"}, hasBreakpoints: true },
	{ selector: ".flex", declarations: {display: "flex"}, hasBreakpoints: true },
	{ selector: ".flow-root", declarations: {display: "flow-root"}, hasBreakpoints: true },
	{ selector: ".grid", declarations: {display: "grid"}, hasBreakpoints: true },
	{ selector: ".inline", declarations: {display: "inline"}, hasBreakpoints: true },
	{ selector: ".inline-block", declarations: {display: "inline-block"}, hasBreakpoints: true },
	{ selector: ".inline-flex", declarations: {display: "inline-flex"}, hasBreakpoints: true },
	{ selector: ".inline-grid", declarations: {display: "inline-grid"}, hasBreakpoints: true },
	{ selector: ".inline-table", declarations: {display: "inline-table"}, hasBreakpoints: true },
	{ selector: ".list-item", declarations: {display: "list-item"}, hasBreakpoints: true },
	{ selector: ".none", declarations: {display: "none"}, hasBreakpoints: true },
	{ selector: ".run-in", declarations: {display: "run-in"}, hasBreakpoints: true },
	{ selector: ".table", declarations: {display: "table"}, hasBreakpoints: true },
	{ selector: ".table-caption", declarations: {display: "table-caption"}, hasBreakpoints: true },
	{ selector: ".table-cell", declarations: {display: "table-cell"}, hasBreakpoints: true },
	{ selector: ".table-column", declarations: {display: "table-column"}, hasBreakpoints: true },
	{ selector: ".table-column-group", declarations: {display: "table-column-group"}, hasBreakpoints: true },
	{ selector: ".table-footer-group", declarations: {display: "table-footer-group"}, hasBreakpoints: true },
	{ selector: ".table-header-group", declarations: {display: "table-header-group"}, hasBreakpoints: true },
	{ selector: ".table-row", declarations: {display: "table-row"}, hasBreakpoints: true },
	{ selector: ".table-row-group", declarations: {display: "table-row-group"}, hasBreakpoints: true },
	{ selector: ".tabel-layout-fixed", declarations: {tableLayout: "fixed"}, hasBreakpoints: true },
	{ selector: ".float-left", declarations: {float: "left"}, hasBreakpoints: true },
	{ selector: ".float-right", declarations: {float: "right"}, hasBreakpoints: true },
];
