import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const margin: Array<FractureRuleType> = [
  { selector: 'm-px', declarations: {margin: 'var(--box-px)'}, hasBreakpoints: true },
  { selector: 'm-1', declarations: {margin: 'var(--box-1)'}, hasBreakpoints: true },
  { selector: 'm-2', declarations: {margin: 'var(--box-2)'}, hasBreakpoints: true },
  { selector: 'm-3', declarations: {margin: 'var(--box-3)'}, hasBreakpoints: true },
  { selector: 'm-4', declarations: {margin: 'var(--box-4)'}, hasBreakpoints: true },
  { selector: 'm-5', declarations: {margin: 'var(--box-5)'}, hasBreakpoints: true },
  { selector: 'm-6', declarations: {margin: 'var(--box-6)'}, hasBreakpoints: true },
  { selector: 'm-7', declarations: {margin: 'var(--box-7)'}, hasBreakpoints: true },
  { selector: 'm-8', declarations: {margin: 'var(--box-8)'}, hasBreakpoints: true },
  { selector: 'm-9', declarations: {margin: 'var(--box-9)'}, hasBreakpoints: true },
  { selector: 'm-10', declarations: {margin: 'var(--box-10)'}, hasBreakpoints: true },
  { selector: 'm-11', declarations: {margin: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'm-11', declarations: {margin: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'm-12', declarations: {margin: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'm-12', declarations: {margin: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'm-13', declarations: {margin: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'm-13', declarations: {margin: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'm-14', declarations: {margin: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'm-14', declarations: {margin: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'm-15', declarations: {margin: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'm-15', declarations: {margin: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'm-16', declarations: {margin: 'var(--box-16)'}, hasBreakpoints: true },
  { selector: 'm-24', declarations: {margin: 'var(--box-24)'}, hasBreakpoints: true },
  { selector: 'm-32', declarations: {margin: 'var(--box-32)'}, hasBreakpoints: true },
  { selector: 'm-40', declarations: {margin: 'var(--box-40)'}, hasBreakpoints: true },
  { selector: 'm-48', declarations: {margin: 'var(--box-48)'}, hasBreakpoints: true },

  { selector: 'mr-px', declarations: {marginRight: 'var(--box-px)'}, hasBreakpoints: true },
  { selector: 'mr-1', declarations: {marginRight: 'var(--box-1)'}, hasBreakpoints: true },
  { selector: 'mr-2', declarations: {marginRight: 'var(--box-2)'}, hasBreakpoints: true },
  { selector: 'mr-3', declarations: {marginRight: 'var(--box-3)'}, hasBreakpoints: true },
  { selector: 'mr-4', declarations: {marginRight: 'var(--box-4)'}, hasBreakpoints: true },
  { selector: 'mr-5', declarations: {marginRight: 'var(--box-5)'}, hasBreakpoints: true },
  { selector: 'mr-6', declarations: {marginRight: 'var(--box-6)'}, hasBreakpoints: true },
  { selector: 'mr-7', declarations: {marginRight: 'var(--box-7)'}, hasBreakpoints: true },
  { selector: 'mr-8', declarations: {marginRight: 'var(--box-8)'}, hasBreakpoints: true },
  { selector: 'mr-9', declarations: {marginRight: 'var(--box-9)'}, hasBreakpoints: true },
  { selector: 'mr-10', declarations: {marginRight: 'var(--box-10)'}, hasBreakpoints: true },
  { selector: 'mr-11', declarations: {marginRight: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'mr-11', declarations: {marginRight: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'mr-12', declarations: {marginRight: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'mr-12', declarations: {marginRight: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'mr-13', declarations: {marginRight: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'mr-13', declarations: {marginRight: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'mr-14', declarations: {marginRight: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'mr-14', declarations: {marginRight: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'mr-15', declarations: {marginRight: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'mr-15', declarations: {marginRight: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'mr-16', declarations: {marginRight: 'var(--box-16)'}, hasBreakpoints: true },
  { selector: 'mr-24', declarations: {marginRight: 'var(--box-24)'}, hasBreakpoints: true },
  { selector: 'mr-32', declarations: {marginRight: 'var(--box-32)'}, hasBreakpoints: true },
  { selector: 'mr-40', declarations: {marginRight: 'var(--box-40)'}, hasBreakpoints: true },
  { selector: 'mr-48', declarations: {marginRight: 'var(--box-48)'}, hasBreakpoints: true },

  { selector: 'ml-px', declarations: {marginLeft: 'var(--box-px)'}, hasBreakpoints: true },
  { selector: 'ml-1', declarations: {marginLeft: 'var(--box-1)'}, hasBreakpoints: true },
  { selector: 'ml-2', declarations: {marginLeft: 'var(--box-2)'}, hasBreakpoints: true },
  { selector: 'ml-3', declarations: {marginLeft: 'var(--box-3)'}, hasBreakpoints: true },
  { selector: 'ml-4', declarations: {marginLeft: 'var(--box-4)'}, hasBreakpoints: true },
  { selector: 'ml-5', declarations: {marginLeft: 'var(--box-5)'}, hasBreakpoints: true },
  { selector: 'ml-6', declarations: {marginLeft: 'var(--box-6)'}, hasBreakpoints: true },
  { selector: 'ml-7', declarations: {marginLeft: 'var(--box-7)'}, hasBreakpoints: true },
  { selector: 'ml-8', declarations: {marginLeft: 'var(--box-8)'}, hasBreakpoints: true },
  { selector: 'ml-9', declarations: {marginLeft: 'var(--box-9)'}, hasBreakpoints: true },
  { selector: 'ml-10', declarations: {marginLeft: 'var(--box-10)'}, hasBreakpoints: true },
  { selector: 'ml-11', declarations: {marginLeft: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'ml-11', declarations: {marginLeft: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'ml-12', declarations: {marginLeft: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'ml-12', declarations: {marginLeft: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'ml-13', declarations: {marginLeft: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'ml-13', declarations: {marginLeft: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'ml-14', declarations: {marginLeft: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'ml-14', declarations: {marginLeft: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'ml-15', declarations: {marginLeft: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'ml-15', declarations: {marginLeft: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'ml-16', declarations: {marginLeft: 'var(--box-16)'}, hasBreakpoints: true },
  { selector: 'ml-24', declarations: {marginLeft: 'var(--box-24)'}, hasBreakpoints: true },
  { selector: 'ml-32', declarations: {marginLeft: 'var(--box-32)'}, hasBreakpoints: true },
  { selector: 'ml-40', declarations: {marginLeft: 'var(--box-40)'}, hasBreakpoints: true },
  { selector: 'ml-48', declarations: {marginLeft: 'var(--box-48)'}, hasBreakpoints: true },

  { selector: 'mt-px', declarations: {marginTop: 'var(--box-px)'}, hasBreakpoints: true },
  { selector: 'mt-1', declarations: {marginTop: 'var(--box-1)'}, hasBreakpoints: true },
  { selector: 'mt-2', declarations: {marginTop: 'var(--box-2)'}, hasBreakpoints: true },
  { selector: 'mt-3', declarations: {marginTop: 'var(--box-3)'}, hasBreakpoints: true },
  { selector: 'mt-4', declarations: {marginTop: 'var(--box-4)'}, hasBreakpoints: true },
  { selector: 'mt-5', declarations: {marginTop: 'var(--box-5)'}, hasBreakpoints: true },
  { selector: 'mt-6', declarations: {marginTop: 'var(--box-6)'}, hasBreakpoints: true },
  { selector: 'mt-7', declarations: {marginTop: 'var(--box-7)'}, hasBreakpoints: true },
  { selector: 'mt-8', declarations: {marginTop: 'var(--box-8)'}, hasBreakpoints: true },
  { selector: 'mt-9', declarations: {marginTop: 'var(--box-9)'}, hasBreakpoints: true },
  { selector: 'mt-10', declarations: {marginTop: 'var(--box-10)'}, hasBreakpoints: true },
  { selector: 'mt-11', declarations: {marginTop: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'mt-11', declarations: {marginTop: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'mt-12', declarations: {marginTop: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'mt-12', declarations: {marginTop: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'mt-13', declarations: {marginTop: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'mt-13', declarations: {marginTop: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'mt-14', declarations: {marginTop: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'mt-14', declarations: {marginTop: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'mt-15', declarations: {marginTop: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'mt-15', declarations: {marginTop: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'mt-16', declarations: {marginTop: 'var(--box-16)'}, hasBreakpoints: true },
  { selector: 'mt-24', declarations: {marginTop: 'var(--box-24)'}, hasBreakpoints: true },
  { selector: 'mt-32', declarations: {marginTop: 'var(--box-32)'}, hasBreakpoints: true },
  { selector: 'mt-40', declarations: {marginTop: 'var(--box-40)'}, hasBreakpoints: true },
  { selector: 'mt-48', declarations: {marginTop: 'var(--box-48)'}, hasBreakpoints: true },

  { selector: 'mb-px', declarations: {marginBottom: 'var(--box-px)'}, hasBreakpoints: true },
  { selector: 'mb-1', declarations: {marginBottom: 'var(--box-1)'}, hasBreakpoints: true },
  { selector: 'mb-2', declarations: {marginBottom: 'var(--box-2)'}, hasBreakpoints: true },
  { selector: 'mb-3', declarations: {marginBottom: 'var(--box-3)'}, hasBreakpoints: true },
  { selector: 'mb-4', declarations: {marginBottom: 'var(--box-4)'}, hasBreakpoints: true },
  { selector: 'mb-5', declarations: {marginBottom: 'var(--box-5)'}, hasBreakpoints: true },
  { selector: 'mb-6', declarations: {marginBottom: 'var(--box-6)'}, hasBreakpoints: true },
  { selector: 'mb-7', declarations: {marginBottom: 'var(--box-7)'}, hasBreakpoints: true },
  { selector: 'mb-8', declarations: {marginBottom: 'var(--box-8)'}, hasBreakpoints: true },
  { selector: 'mb-9', declarations: {marginBottom: 'var(--box-9)'}, hasBreakpoints: true },
  { selector: 'mb-10', declarations: {marginBottom: 'var(--box-10)'}, hasBreakpoints: true },
  { selector: 'mb-11', declarations: {marginBottom: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'mb-11', declarations: {marginBottom: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'mb-12', declarations: {marginBottom: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'mb-12', declarations: {marginBottom: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'mb-13', declarations: {marginBottom: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'mb-13', declarations: {marginBottom: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'mb-14', declarations: {marginBottom: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'mb-14', declarations: {marginBottom: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'mb-15', declarations: {marginBottom: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'mb-15', declarations: {marginBottom: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'mb-16', declarations: {marginBottom: 'var(--box-16)'}, hasBreakpoints: true },
  { selector: 'mb-24', declarations: {marginBottom: 'var(--box-24)'}, hasBreakpoints: true },
  { selector: 'mb-32', declarations: {marginBottom: 'var(--box-32)'}, hasBreakpoints: true },
  { selector: 'mb-40', declarations: {marginBottom: 'var(--box-40)'}, hasBreakpoints: true },
  { selector: 'mb-48', declarations: {marginBottom: 'var(--box-48)'}, hasBreakpoints: true },

  { selector: 'my-px', declarations: {marginTop: 'var(--box-px)', marginBottom: 'var(--box-px)'}, hasBreakpoints: true },
  { selector: 'my-1', declarations: {marginTop: 'var(--box-1)', marginBottom: 'var(--box-1)'}, hasBreakpoints: true },
  { selector: 'my-2', declarations: {marginTop: 'var(--box-2)', marginBottom: 'var(--box-2)'}, hasBreakpoints: true },
  { selector: 'my-3', declarations: {marginTop: 'var(--box-3)', marginBottom: 'var(--box-3)'}, hasBreakpoints: true },
  { selector: 'my-4', declarations: {marginTop: 'var(--box-4)', marginBottom: 'var(--box-4)'}, hasBreakpoints: true },
  { selector: 'my-5', declarations: {marginTop: 'var(--box-5)', marginBottom: 'var(--box-5)'}, hasBreakpoints: true },
  { selector: 'my-6', declarations: {marginTop: 'var(--box-6)', marginBottom: 'var(--box-6)'}, hasBreakpoints: true },
  { selector: 'my-7', declarations: {marginTop: 'var(--box-7)', marginBottom: 'var(--box-7)'}, hasBreakpoints: true },
  { selector: 'my-8', declarations: {marginTop: 'var(--box-8)', marginBottom: 'var(--box-8)'}, hasBreakpoints: true },
  { selector: 'my-9', declarations: {marginTop: 'var(--box-9)', marginBottom: 'var(--box-9)'}, hasBreakpoints: true },
  { selector: 'my-10', declarations: {marginTop: 'var(--box-10)', marginBottom: 'var(--box-10)'}, hasBreakpoints: true },
  { selector: 'my-11', declarations: {marginTop: 'var(--box-11)', marginBottom: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'my-11', declarations: {marginTop: 'var(--box-11)', marginBottom: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'my-12', declarations: {marginTop: 'var(--box-12)', marginBottom: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'my-12', declarations: {marginTop: 'var(--box-12)', marginBottom: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'my-13', declarations: {marginTop: 'var(--box-13)', marginBottom: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'my-13', declarations: {marginTop: 'var(--box-13)', marginBottom: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'my-14', declarations: {marginTop: 'var(--box-14)', marginBottom: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'my-14', declarations: {marginTop: 'var(--box-14)', marginBottom: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'my-15', declarations: {marginTop: 'var(--box-15)', marginBottom: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'my-15', declarations: {marginTop: 'var(--box-15)', marginBottom: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'my-16', declarations: {marginTop: 'var(--box-16)', marginBottom: 'var(--box-16)'}, hasBreakpoints: true },
  { selector: 'my-24', declarations: {marginTop: 'var(--box-24)', marginBottom: 'var(--box-24)'}, hasBreakpoints: true },
  { selector: 'my-32', declarations: {marginTop: 'var(--box-32)', marginBottom: 'var(--box-32)'}, hasBreakpoints: true },
  { selector: 'my-40', declarations: {marginTop: 'var(--box-40)', marginBottom: 'var(--box-40)'}, hasBreakpoints: true },
  { selector: 'my-48', declarations: {marginTop: 'var(--box-48)', marginBottom: 'var(--box-48)'}, hasBreakpoints: true },

  { selector: 'mx-auto', declarations: {marginLeft: 'auto', marginRight: 'auto'}, hasBreakpoints: true },
  { selector: 'mx-px', declarations: {marginLeft: 'var(--box-px)', marginRight: 'var(--box-px)'}, hasBreakpoints: true },
  { selector: 'mx-1', declarations: {marginLeft: 'var(--box-1)', marginRight: 'var(--box-1)'}, hasBreakpoints: true },
  { selector: 'mx-2', declarations: {marginLeft: 'var(--box-2)', marginRight: 'var(--box-2)'}, hasBreakpoints: true },
  { selector: 'mx-3', declarations: {marginLeft: 'var(--box-3)', marginRight: 'var(--box-3)'}, hasBreakpoints: true },
  { selector: 'mx-4', declarations: {marginLeft: 'var(--box-4)', marginRight: 'var(--box-4)'}, hasBreakpoints: true },
  { selector: 'mx-5', declarations: {marginLeft: 'var(--box-5)', marginRight: 'var(--box-5)'}, hasBreakpoints: true },
  { selector: 'mx-6', declarations: {marginLeft: 'var(--box-6)', marginRight: 'var(--box-6)'}, hasBreakpoints: true },
  { selector: 'mx-7', declarations: {marginLeft: 'var(--box-7)', marginRight: 'var(--box-7)'}, hasBreakpoints: true },
  { selector: 'mx-8', declarations: {marginLeft: 'var(--box-8)', marginRight: 'var(--box-8)'}, hasBreakpoints: true },
  { selector: 'mx-9', declarations: {marginLeft: 'var(--box-9)', marginRight: 'var(--box-9)'}, hasBreakpoints: true },
  { selector: 'mx-10', declarations: {marginLeft: 'var(--box-10)', marginRight: 'var(--box-10)'}, hasBreakpoints: true },
  { selector: 'mx-11', declarations: {marginLeft: 'var(--box-11)', marginRight: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'mx-11', declarations: {marginLeft: 'var(--box-11)', marginRight: 'var(--box-11)'}, hasBreakpoints: true },
  { selector: 'mx-12', declarations: {marginLeft: 'var(--box-12)', marginRight: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'mx-12', declarations: {marginLeft: 'var(--box-12)', marginRight: 'var(--box-12)'}, hasBreakpoints: true },
  { selector: 'mx-13', declarations: {marginLeft: 'var(--box-13)', marginRight: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'mx-13', declarations: {marginLeft: 'var(--box-13)', marginRight: 'var(--box-13)'}, hasBreakpoints: true },
  { selector: 'mx-14', declarations: {marginLeft: 'var(--box-14)', marginRight: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'mx-14', declarations: {marginLeft: 'var(--box-14)', marginRight: 'var(--box-14)'}, hasBreakpoints: true },
  { selector: 'mx-15', declarations: {marginLeft: 'var(--box-15)', marginRight: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'mx-15', declarations: {marginLeft: 'var(--box-15)', marginRight: 'var(--box-15)'}, hasBreakpoints: true },
  { selector: 'mx-16', declarations: {marginLeft: 'var(--box-16)', marginRight: 'var(--box-16)'}, hasBreakpoints: true },
  { selector: 'mx-24', declarations: {marginLeft: 'var(--box-24)', marginRight: 'var(--box-24)'}, hasBreakpoints: true },
  { selector: 'mx-32', declarations: {marginLeft: 'var(--box-32)', marginRight: 'var(--box-32)'}, hasBreakpoints: true },
  { selector: 'mx-40', declarations: {marginLeft: 'var(--box-40)', marginRight: 'var(--box-40)'}, hasBreakpoints: true },
  { selector: 'mx-48', declarations: {marginLeft: 'var(--box-48)', marginRight: 'var(--box-48)'}, hasBreakpoints: true },
];
