import type { FractureRuleType } from "../../types/css-rules";

export const padding: Array<FractureRuleType> = [
  { selector: 'p-px', declarations: { padding: 'var(--box-px)' }, hasBreakpoints: true },
  { selector: 'p-0', declarations: { padding: '0' }, hasBreakpoints: true },
  { selector: 'p-1', declarations: { padding: 'var(--box-1)' }, hasBreakpoints: true },
  { selector: 'p-2', declarations: { padding: 'var(--box-2)' }, hasBreakpoints: true },
  { selector: 'p-3', declarations: { padding: 'var(--box-3)' }, hasBreakpoints: true },
  { selector: 'p-4', declarations: { padding: 'var(--box-4)' }, hasBreakpoints: true },
  { selector: 'p-5', declarations: { padding: 'var(--box-5)' }, hasBreakpoints: true },
  { selector: 'p-6', declarations: { padding: 'var(--box-6)' }, hasBreakpoints: true },
  { selector: 'p-7', declarations: { padding: 'var(--box-7)' }, hasBreakpoints: true },
  { selector: 'p-8', declarations: { padding: 'var(--box-8)' }, hasBreakpoints: true },
  { selector: 'p-9', declarations: { padding: 'var(--box-9)' }, hasBreakpoints: true },
  { selector: 'p-10', declarations: { padding: 'var(--box-10)' }, hasBreakpoints: true },
  { selector: 'p-11', declarations: { padding: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'p-11', declarations: { padding: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'p-12', declarations: { padding: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'p-12', declarations: { padding: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'p-13', declarations: { padding: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'p-13', declarations: { padding: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'p-14', declarations: { padding: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'p-14', declarations: { padding: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'p-15', declarations: { padding: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'p-15', declarations: { padding: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'p-16', declarations: { padding: 'var(--box-16)' }, hasBreakpoints: true },
  { selector: 'p-24', declarations: { padding: 'var(--box-24)' }, hasBreakpoints: true },
  { selector: 'p-32', declarations: { padding: 'var(--box-32)' }, hasBreakpoints: true },
  { selector: 'p-40', declarations: { padding: 'var(--box-40)' }, hasBreakpoints: true },
  { selector: 'p-48', declarations: { padding: 'var(--box-48)' }, hasBreakpoints: true },

  { selector: 'pr-px', declarations: { paddingRight: 'var(--box-px)' }, hasBreakpoints: true },
  { selector: 'pr-0', declarations: { paddingRight: '0' }, hasBreakpoints: true },
  { selector: 'pr-1', declarations: { paddingRight: 'var(--box-1)' }, hasBreakpoints: true },
  { selector: 'pr-2', declarations: { paddingRight: 'var(--box-2)' }, hasBreakpoints: true },
  { selector: 'pr-3', declarations: { paddingRight: 'var(--box-3)' }, hasBreakpoints: true },
  { selector: 'pr-4', declarations: { paddingRight: 'var(--box-4)' }, hasBreakpoints: true },
  { selector: 'pr-5', declarations: { paddingRight: 'var(--box-5)' }, hasBreakpoints: true },
  { selector: 'pr-6', declarations: { paddingRight: 'var(--box-6)' }, hasBreakpoints: true },
  { selector: 'pr-7', declarations: { paddingRight: 'var(--box-7)' }, hasBreakpoints: true },
  { selector: 'pr-8', declarations: { paddingRight: 'var(--box-8)' }, hasBreakpoints: true },
  { selector: 'pr-9', declarations: { paddingRight: 'var(--box-9)' }, hasBreakpoints: true },
  { selector: 'pr-10', declarations: { paddingRight: 'var(--box-10)' }, hasBreakpoints: true },
  { selector: 'pr-11', declarations: { paddingRight: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'pr-11', declarations: { paddingRight: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'pr-12', declarations: { paddingRight: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'pr-12', declarations: { paddingRight: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'pr-13', declarations: { paddingRight: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'pr-13', declarations: { paddingRight: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'pr-14', declarations: { paddingRight: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'pr-14', declarations: { paddingRight: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'pr-15', declarations: { paddingRight: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'pr-15', declarations: { paddingRight: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'pr-16', declarations: { paddingRight: 'var(--box-16)' }, hasBreakpoints: true },
  { selector: 'pr-24', declarations: { paddingRight: 'var(--box-24)' }, hasBreakpoints: true },
  { selector: 'pr-32', declarations: { paddingRight: 'var(--box-32)' }, hasBreakpoints: true },
  { selector: 'pr-40', declarations: { paddingRight: 'var(--box-40)' }, hasBreakpoints: true },
  { selector: 'pr-48', declarations: { paddingRight: 'var(--box-48)' }, hasBreakpoints: true },

  { selector: 'pl-px', declarations: { paddingLeft: 'var(--box-px)' }, hasBreakpoints: true },
  { selector: 'pl-0', declarations: { paddingLeft: '0' }, hasBreakpoints: true },
  { selector: 'pl-1', declarations: { paddingLeft: 'var(--box-1)' }, hasBreakpoints: true },
  { selector: 'pl-2', declarations: { paddingLeft: 'var(--box-2)' }, hasBreakpoints: true },
  { selector: 'pl-3', declarations: { paddingLeft: 'var(--box-3)' }, hasBreakpoints: true },
  { selector: 'pl-4', declarations: { paddingLeft: 'var(--box-4)' }, hasBreakpoints: true },
  { selector: 'pl-5', declarations: { paddingLeft: 'var(--box-5)' }, hasBreakpoints: true },
  { selector: 'pl-6', declarations: { paddingLeft: 'var(--box-6)' }, hasBreakpoints: true },
  { selector: 'pl-7', declarations: { paddingLeft: 'var(--box-7)' }, hasBreakpoints: true },
  { selector: 'pl-8', declarations: { paddingLeft: 'var(--box-8)' }, hasBreakpoints: true },
  { selector: 'pl-9', declarations: { paddingLeft: 'var(--box-9)' }, hasBreakpoints: true },
  { selector: 'pl-10', declarations: { paddingLeft: 'var(--box-10)' }, hasBreakpoints: true },
  { selector: 'pl-11', declarations: { paddingLeft: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'pl-11', declarations: { paddingLeft: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'pl-12', declarations: { paddingLeft: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'pl-12', declarations: { paddingLeft: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'pl-13', declarations: { paddingLeft: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'pl-13', declarations: { paddingLeft: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'pl-14', declarations: { paddingLeft: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'pl-14', declarations: { paddingLeft: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'pl-15', declarations: { paddingLeft: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'pl-15', declarations: { paddingLeft: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'pl-16', declarations: { paddingLeft: 'var(--box-16)' }, hasBreakpoints: true },
  { selector: 'pl-24', declarations: { paddingLeft: 'var(--box-24)' }, hasBreakpoints: true },
  { selector: 'pl-32', declarations: { paddingLeft: 'var(--box-32)' }, hasBreakpoints: true },
  { selector: 'pl-40', declarations: { paddingLeft: 'var(--box-40)' }, hasBreakpoints: true },
  { selector: 'pl-48', declarations: { paddingLeft: 'var(--box-48)' }, hasBreakpoints: true },

  { selector: 'pt-px', declarations: { paddingTop: 'var(--box-px)' }, hasBreakpoints: true },
  { selector: 'pt-0', declarations: { paddingTop: '0' }, hasBreakpoints: true },
  { selector: 'pt-1', declarations: { paddingTop: 'var(--box-1)' }, hasBreakpoints: true },
  { selector: 'pt-2', declarations: { paddingTop: 'var(--box-2)' }, hasBreakpoints: true },
  { selector: 'pt-3', declarations: { paddingTop: 'var(--box-3)' }, hasBreakpoints: true },
  { selector: 'pt-4', declarations: { paddingTop: 'var(--box-4)' }, hasBreakpoints: true },
  { selector: 'pt-5', declarations: { paddingTop: 'var(--box-5)' }, hasBreakpoints: true },
  { selector: 'pt-6', declarations: { paddingTop: 'var(--box-6)' }, hasBreakpoints: true },
  { selector: 'pt-7', declarations: { paddingTop: 'var(--box-7)' }, hasBreakpoints: true },
  { selector: 'pt-8', declarations: { paddingTop: 'var(--box-8)' }, hasBreakpoints: true },
  { selector: 'pt-9', declarations: { paddingTop: 'var(--box-9)' }, hasBreakpoints: true },
  { selector: 'pt-10', declarations: { paddingTop: 'var(--box-10)' }, hasBreakpoints: true },
  { selector: 'pt-11', declarations: { paddingTop: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'pt-11', declarations: { paddingTop: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'pt-12', declarations: { paddingTop: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'pt-12', declarations: { paddingTop: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'pt-13', declarations: { paddingTop: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'pt-13', declarations: { paddingTop: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'pt-14', declarations: { paddingTop: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'pt-14', declarations: { paddingTop: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'pt-15', declarations: { paddingTop: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'pt-15', declarations: { paddingTop: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'pt-16', declarations: { paddingTop: 'var(--box-16)' }, hasBreakpoints: true },
  { selector: 'pt-24', declarations: { paddingTop: 'var(--box-24)' }, hasBreakpoints: true },
  { selector: 'pt-32', declarations: { paddingTop: 'var(--box-32)' }, hasBreakpoints: true },
  { selector: 'pt-40', declarations: { paddingTop: 'var(--box-40)' }, hasBreakpoints: true },
  { selector: 'pt-48', declarations: { paddingTop: 'var(--box-48)' }, hasBreakpoints: true },

  { selector: 'pb-px', declarations: { paddingBottom: 'var(--box-px)' }, hasBreakpoints: true },
  { selector: 'pb-0', declarations: { paddingBottom: '0' }, hasBreakpoints: true },
  { selector: 'pb-1', declarations: { paddingBottom: 'var(--box-1)' }, hasBreakpoints: true },
  { selector: 'pb-2', declarations: { paddingBottom: 'var(--box-2)' }, hasBreakpoints: true },
  { selector: 'pb-3', declarations: { paddingBottom: 'var(--box-3)' }, hasBreakpoints: true },
  { selector: 'pb-4', declarations: { paddingBottom: 'var(--box-4)' }, hasBreakpoints: true },
  { selector: 'pb-5', declarations: { paddingBottom: 'var(--box-5)' }, hasBreakpoints: true },
  { selector: 'pb-6', declarations: { paddingBottom: 'var(--box-6)' }, hasBreakpoints: true },
  { selector: 'pb-7', declarations: { paddingBottom: 'var(--box-7)' }, hasBreakpoints: true },
  { selector: 'pb-8', declarations: { paddingBottom: 'var(--box-8)' }, hasBreakpoints: true },
  { selector: 'pb-9', declarations: { paddingBottom: 'var(--box-9)' }, hasBreakpoints: true },
  { selector: 'pb-10', declarations: { paddingBottom: 'var(--box-10)' }, hasBreakpoints: true },
  { selector: 'pb-11', declarations: { paddingBottom: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'pb-11', declarations: { paddingBottom: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'pb-12', declarations: { paddingBottom: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'pb-12', declarations: { paddingBottom: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'pb-13', declarations: { paddingBottom: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'pb-13', declarations: { paddingBottom: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'pb-14', declarations: { paddingBottom: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'pb-14', declarations: { paddingBottom: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'pb-15', declarations: { paddingBottom: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'pb-15', declarations: { paddingBottom: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'pb-16', declarations: { paddingBottom: 'var(--box-16)' }, hasBreakpoints: true },
  { selector: 'pb-24', declarations: { paddingBottom: 'var(--box-24)' }, hasBreakpoints: true },
  { selector: 'pb-32', declarations: { paddingBottom: 'var(--box-32)' }, hasBreakpoints: true },
  { selector: 'pb-40', declarations: { paddingBottom: 'var(--box-40)' }, hasBreakpoints: true },
  { selector: 'pb-48', declarations: { paddingBottom: 'var(--box-48)' }, hasBreakpoints: true },

  { selector: 'py-px', declarations: { paddingBottom: 'var(--box-px)', paddingTop: 'var(--box-px)' }, hasBreakpoints: true },
  { selector: 'py-0', declarations: { paddingBottom: '0', paddingTop: '0' }, hasBreakpoints: true },
  { selector: 'py-1', declarations: { paddingBottom: 'var(--box-1)', paddingTop: 'var(--box-1)' }, hasBreakpoints: true },
  { selector: 'py-2', declarations: { paddingBottom: 'var(--box-2)', paddingTop: 'var(--box-2)' }, hasBreakpoints: true },
  { selector: 'py-3', declarations: { paddingBottom: 'var(--box-3)', paddingTop: 'var(--box-3)' }, hasBreakpoints: true },
  { selector: 'py-4', declarations: { paddingBottom: 'var(--box-4)', paddingTop: 'var(--box-4)' }, hasBreakpoints: true },
  { selector: 'py-5', declarations: { paddingBottom: 'var(--box-5)', paddingTop: 'var(--box-5)' }, hasBreakpoints: true },
  { selector: 'py-6', declarations: { paddingBottom: 'var(--box-6)', paddingTop: 'var(--box-6)' }, hasBreakpoints: true },
  { selector: 'py-7', declarations: { paddingBottom: 'var(--box-7)', paddingTop: 'var(--box-7)' }, hasBreakpoints: true },
  { selector: 'py-8', declarations: { paddingBottom: 'var(--box-8)', paddingTop: 'var(--box-8)' }, hasBreakpoints: true },
  { selector: 'py-9', declarations: { paddingBottom: 'var(--box-9)', paddingTop: 'var(--box-9)' }, hasBreakpoints: true },
  { selector: 'py-10', declarations: { paddingBottom: 'var(--box-10)', paddingTop: 'var(--box-10)' }, hasBreakpoints: true },
  { selector: 'py-11', declarations: { paddingBottom: 'var(--box-11)', paddingTop: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'py-11', declarations: { paddingBottom: 'var(--box-11)', paddingTop: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'py-12', declarations: { paddingBottom: 'var(--box-12)', paddingTop: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'py-12', declarations: { paddingBottom: 'var(--box-12)', paddingTop: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'py-13', declarations: { paddingBottom: 'var(--box-13)', paddingTop: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'py-13', declarations: { paddingBottom: 'var(--box-13)', paddingTop: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'py-14', declarations: { paddingBottom: 'var(--box-14)', paddingTop: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'py-14', declarations: { paddingBottom: 'var(--box-14)', paddingTop: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'py-15', declarations: { paddingBottom: 'var(--box-15)', paddingTop: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'py-15', declarations: { paddingBottom: 'var(--box-15)', paddingTop: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'py-16', declarations: { paddingBottom: 'var(--box-16)', paddingTop: 'var(--box-16)' }, hasBreakpoints: true },
  { selector: 'py-24', declarations: { paddingBottom: 'var(--box-24)', paddingTop: 'var(--box-24)' }, hasBreakpoints: true },
  { selector: 'py-32', declarations: { paddingBottom: 'var(--box-32)', paddingTop: 'var(--box-32)' }, hasBreakpoints: true },
  { selector: 'py-40', declarations: { paddingBottom: 'var(--box-40)', paddingTop: 'var(--box-40)' }, hasBreakpoints: true },
  { selector: 'py-48', declarations: { paddingBottom: 'var(--box-48)', paddingTop: 'var(--box-48)' }, hasBreakpoints: true },

  { selector: 'px-px', declarations: { paddingLeft: 'var(--box-px)', paddingRight: 'var(--box-px)' }, hasBreakpoints: true },
  { selector: 'px-0', declarations: { paddingLeft: '0', paddingRight: '0' }, hasBreakpoints: true },
  { selector: 'px-1', declarations: { paddingLeft: 'var(--box-1)', paddingRight: 'var(--box-1)' }, hasBreakpoints: true },
  { selector: 'px-2', declarations: { paddingLeft: 'var(--box-2)', paddingRight: 'var(--box-2)' }, hasBreakpoints: true },
  { selector: 'px-3', declarations: { paddingLeft: 'var(--box-3)', paddingRight: 'var(--box-3)' }, hasBreakpoints: true },
  { selector: 'px-4', declarations: { paddingLeft: 'var(--box-4)', paddingRight: 'var(--box-4)' }, hasBreakpoints: true },
  { selector: 'px-5', declarations: { paddingLeft: 'var(--box-5)', paddingRight: 'var(--box-5)' }, hasBreakpoints: true },
  { selector: 'px-6', declarations: { paddingLeft: 'var(--box-6)', paddingRight: 'var(--box-6)' }, hasBreakpoints: true },
  { selector: 'px-7', declarations: { paddingLeft: 'var(--box-7)', paddingRight: 'var(--box-7)' }, hasBreakpoints: true },
  { selector: 'px-8', declarations: { paddingLeft: 'var(--box-8)', paddingRight: 'var(--box-8)' }, hasBreakpoints: true },
  { selector: 'px-9', declarations: { paddingLeft: 'var(--box-9)', paddingRight: 'var(--box-9)' }, hasBreakpoints: true },
  { selector: 'px-10', declarations: { paddingLeft: 'var(--box-10)', paddingRight: 'var(--box-10)' }, hasBreakpoints: true },
  { selector: 'px-11', declarations: { paddingLeft: 'var(--box-11)', paddingRight: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'px-11', declarations: { paddingLeft: 'var(--box-11)', paddingRight: 'var(--box-11)' }, hasBreakpoints: true },
  { selector: 'px-12', declarations: { paddingLeft: 'var(--box-12)', paddingRight: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'px-12', declarations: { paddingLeft: 'var(--box-12)', paddingRight: 'var(--box-12)' }, hasBreakpoints: true },
  { selector: 'px-13', declarations: { paddingLeft: 'var(--box-13)', paddingRight: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'px-13', declarations: { paddingLeft: 'var(--box-13)', paddingRight: 'var(--box-13)' }, hasBreakpoints: true },
  { selector: 'px-14', declarations: { paddingLeft: 'var(--box-14)', paddingRight: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'px-14', declarations: { paddingLeft: 'var(--box-14)', paddingRight: 'var(--box-14)' }, hasBreakpoints: true },
  { selector: 'px-15', declarations: { paddingLeft: 'var(--box-15)', paddingRight: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'px-15', declarations: { paddingLeft: 'var(--box-15)', paddingRight: 'var(--box-15)' }, hasBreakpoints: true },
  { selector: 'px-16', declarations: { paddingLeft: 'var(--box-16)', paddingRight: 'var(--box-16)' }, hasBreakpoints: true },
  { selector: 'px-24', declarations: { paddingLeft: 'var(--box-24)', paddingRight: 'var(--box-24)' }, hasBreakpoints: true },
  { selector: 'px-32', declarations: { paddingLeft: 'var(--box-32)', paddingRight: 'var(--box-32)' }, hasBreakpoints: true },
  { selector: 'px-40', declarations: { paddingLeft: 'var(--box-40)', paddingRight: 'var(--box-40)' }, hasBreakpoints: true },
  { selector: 'px-48', declarations: { paddingLeft: 'var(--box-48)', paddingRight: 'var(--box-48)' }, hasBreakpoints: true },
];
