import type { FractureRuleType } from "../../types/css-rules";

// TODO needs responsive flag

// prettier-ignore
export const padding: Array<FractureRuleType> = [
{ selector: 'p-px', property: 'padding', value: 'var(--box-px)' },
{ selector: 'p-1', property: 'padding', value: 'var(--box-1)' },
{ selector: 'p-2', property: 'padding', value: 'var(--box-2)' },
{ selector: 'p-3', property: 'padding', value: 'var(--box-3)' },
{ selector: 'p-4', property: 'padding', value: 'var(--box-4)' },
{ selector: 'p-5', property: 'padding', value: 'var(--box-5)' },
{ selector: 'p-6', property: 'padding', value: 'var(--box-6)' },
{ selector: 'p-7', property: 'padding', value: 'var(--box-7)' },
{ selector: 'p-8', property: 'padding', value: 'var(--box-8)' },
{ selector: 'p-9', property: 'padding', value: 'var(--box-9)' },
{ selector: 'p-10', property: 'padding', value: 'var(--box-10)' },
{ selector: 'p-11', property: 'padding', value: 'var(--box-11)' },
{ selector: 'p-11', property: 'padding', value: 'var(--box-11)' },
{ selector: 'p-12', property: 'padding', value: 'var(--box-12)' },
{ selector: 'p-12', property: 'padding', value: 'var(--box-12)' },
{ selector: 'p-13', property: 'padding', value: 'var(--box-13)' },
{ selector: 'p-13', property: 'padding', value: 'var(--box-13)' },
{ selector: 'p-14', property: 'padding', value: 'var(--box-14)' },
{ selector: 'p-14', property: 'padding', value: 'var(--box-14)' },
{ selector: 'p-15', property: 'padding', value: 'var(--box-15)' },
{ selector: 'p-15', property: 'padding', value: 'var(--box-15)' },
{ selector: 'p-16', property: 'padding', value: 'var(--box-16)' },
{ selector: 'p-24', property: 'padding', value: 'var(--box-24)' },
{ selector: 'p-32', property: 'padding', value: 'var(--box-32)' },
{ selector: 'p-40', property: 'padding', value: 'var(--box-40)' },
{ selector: 'p-48', property: 'padding', value: 'var(--box-48)' },

{ selector: 'pr-px', property: 'padding-right', value: 'var(--box-px)' },
{ selector: 'pr-1', property: 'padding-right', value: 'var(--box-1)' },
{ selector: 'pr-2', property: 'padding-right', value: 'var(--box-2)' },
{ selector: 'pr-3', property: 'padding-right', value: 'var(--box-3)' },
{ selector: 'pr-4', property: 'padding-right', value: 'var(--box-4)' },
{ selector: 'pr-5', property: 'padding-right', value: 'var(--box-5)' },
{ selector: 'pr-6', property: 'padding-right', value: 'var(--box-6)' },
{ selector: 'pr-7', property: 'padding-right', value: 'var(--box-7)' },
{ selector: 'pr-8', property: 'padding-right', value: 'var(--box-8)' },
{ selector: 'pr-9', property: 'padding-right', value: 'var(--box-9)' },
{ selector: 'pr-10', property: 'padding-right', value: 'var(--box-10)' },
{ selector: 'pr-11', property: 'padding-right', value: 'var(--box-11)' },
{ selector: 'pr-11', property: 'padding-right', value: 'var(--box-11)' },
{ selector: 'pr-12', property: 'padding-right', value: 'var(--box-12)' },
{ selector: 'pr-12', property: 'padding-right', value: 'var(--box-12)' },
{ selector: 'pr-13', property: 'padding-right', value: 'var(--box-13)' },
{ selector: 'pr-13', property: 'padding-right', value: 'var(--box-13)' },
{ selector: 'pr-14', property: 'padding-right', value: 'var(--box-14)' },
{ selector: 'pr-14', property: 'padding-right', value: 'var(--box-14)' },
{ selector: 'pr-15', property: 'padding-right', value: 'var(--box-15)' },
{ selector: 'pr-15', property: 'padding-right', value: 'var(--box-15)' },
{ selector: 'pr-16', property: 'padding-right', value: 'var(--box-16)' },
{ selector: 'pr-24', property: 'padding-right', value: 'var(--box-24)' },
{ selector: 'pr-32', property: 'padding-right', value: 'var(--box-32)' },
{ selector: 'pr-40', property: 'padding-right', value: 'var(--box-40)' },
{ selector: 'pr-48', property: 'padding-right', value: 'var(--box-48)' },

{ selector: 'pl-px', property: 'padding-left', value: 'var(--box-px)' },
{ selector: 'pl-1', property: 'padding-left', value: 'var(--box-1)' },
{ selector: 'pl-2', property: 'padding-left', value: 'var(--box-2)' },
{ selector: 'pl-3', property: 'padding-left', value: 'var(--box-3)' },
{ selector: 'pl-4', property: 'padding-left', value: 'var(--box-4)' },
{ selector: 'pl-5', property: 'padding-left', value: 'var(--box-5)' },
{ selector: 'pl-6', property: 'padding-left', value: 'var(--box-6)' },
{ selector: 'pl-7', property: 'padding-left', value: 'var(--box-7)' },
{ selector: 'pl-8', property: 'padding-left', value: 'var(--box-8)' },
{ selector: 'pl-9', property: 'padding-left', value: 'var(--box-9)' },
{ selector: 'pl-10', property: 'padding-left', value: 'var(--box-10)' },
{ selector: 'pl-11', property: 'padding-left', value: 'var(--box-11)' },
{ selector: 'pl-11', property: 'padding-left', value: 'var(--box-11)' },
{ selector: 'pl-12', property: 'padding-left', value: 'var(--box-12)' },
{ selector: 'pl-12', property: 'padding-left', value: 'var(--box-12)' },
{ selector: 'pl-13', property: 'padding-left', value: 'var(--box-13)' },
{ selector: 'pl-13', property: 'padding-left', value: 'var(--box-13)' },
{ selector: 'pl-14', property: 'padding-left', value: 'var(--box-14)' },
{ selector: 'pl-14', property: 'padding-left', value: 'var(--box-14)' },
{ selector: 'pl-15', property: 'padding-left', value: 'var(--box-15)' },
{ selector: 'pl-15', property: 'padding-left', value: 'var(--box-15)' },
{ selector: 'pl-16', property: 'padding-left', value: 'var(--box-16)' },
{ selector: 'pl-24', property: 'padding-left', value: 'var(--box-24)' },
{ selector: 'pl-32', property: 'padding-left', value: 'var(--box-32)' },
{ selector: 'pl-40', property: 'padding-left', value: 'var(--box-40)' },
{ selector: 'pl-48', property: 'padding-left', value: 'var(--box-48)' },

{ selector: 'pt-px', property: 'padding-top', value: 'var(--box-px)' },
{ selector: 'pt-1', property: 'padding-top', value: 'var(--box-1)' },
{ selector: 'pt-2', property: 'padding-top', value: 'var(--box-2)' },
{ selector: 'pt-3', property: 'padding-top', value: 'var(--box-3)' },
{ selector: 'pt-4', property: 'padding-top', value: 'var(--box-4)' },
{ selector: 'pt-5', property: 'padding-top', value: 'var(--box-5)' },
{ selector: 'pt-6', property: 'padding-top', value: 'var(--box-6)' },
{ selector: 'pt-7', property: 'padding-top', value: 'var(--box-7)' },
{ selector: 'pt-8', property: 'padding-top', value: 'var(--box-8)' },
{ selector: 'pt-9', property: 'padding-top', value: 'var(--box-9)' },
{ selector: 'pt-10', property: 'padding-top', value: 'var(--box-10)' },
{ selector: 'pt-11', property: 'padding-top', value: 'var(--box-11)' },
{ selector: 'pt-11', property: 'padding-top', value: 'var(--box-11)' },
{ selector: 'pt-12', property: 'padding-top', value: 'var(--box-12)' },
{ selector: 'pt-12', property: 'padding-top', value: 'var(--box-12)' },
{ selector: 'pt-13', property: 'padding-top', value: 'var(--box-13)' },
{ selector: 'pt-13', property: 'padding-top', value: 'var(--box-13)' },
{ selector: 'pt-14', property: 'padding-top', value: 'var(--box-14)' },
{ selector: 'pt-14', property: 'padding-top', value: 'var(--box-14)' },
{ selector: 'pt-15', property: 'padding-top', value: 'var(--box-15)' },
{ selector: 'pt-15', property: 'padding-top', value: 'var(--box-15)' },
{ selector: 'pt-16', property: 'padding-top', value: 'var(--box-16)' },
{ selector: 'pt-24', property: 'padding-top', value: 'var(--box-24)' },
{ selector: 'pt-32', property: 'padding-top', value: 'var(--box-32)' },
{ selector: 'pt-40', property: 'padding-top', value: 'var(--box-40)' },
{ selector: 'pt-48', property: 'padding-top', value: 'var(--box-48)' },

{ selector: 'pb-px', property: 'padding-bottom', value: 'var(--box-px)' },
{ selector: 'pb-1', property: 'padding-bottom', value: 'var(--box-1)' },
{ selector: 'pb-2', property: 'padding-bottom', value: 'var(--box-2)' },
{ selector: 'pb-3', property: 'padding-bottom', value: 'var(--box-3)' },
{ selector: 'pb-4', property: 'padding-bottom', value: 'var(--box-4)' },
{ selector: 'pb-5', property: 'padding-bottom', value: 'var(--box-5)' },
{ selector: 'pb-6', property: 'padding-bottom', value: 'var(--box-6)' },
{ selector: 'pb-7', property: 'padding-bottom', value: 'var(--box-7)' },
{ selector: 'pb-8', property: 'padding-bottom', value: 'var(--box-8)' },
{ selector: 'pb-9', property: 'padding-bottom', value: 'var(--box-9)' },
{ selector: 'pb-10', property: 'padding-bottom', value: 'var(--box-10)' },
{ selector: 'pb-11', property: 'padding-bottom', value: 'var(--box-11)' },
{ selector: 'pb-11', property: 'padding-bottom', value: 'var(--box-11)' },
{ selector: 'pb-12', property: 'padding-bottom', value: 'var(--box-12)' },
{ selector: 'pb-12', property: 'padding-bottom', value: 'var(--box-12)' },
{ selector: 'pb-13', property: 'padding-bottom', value: 'var(--box-13)' },
{ selector: 'pb-13', property: 'padding-bottom', value: 'var(--box-13)' },
{ selector: 'pb-14', property: 'padding-bottom', value: 'var(--box-14)' },
{ selector: 'pb-14', property: 'padding-bottom', value: 'var(--box-14)' },
{ selector: 'pb-15', property: 'padding-bottom', value: 'var(--box-15)' },
{ selector: 'pb-15', property: 'padding-bottom', value: 'var(--box-15)' },
{ selector: 'pb-16', property: 'padding-bottom', value: 'var(--box-16)' },
{ selector: 'pb-24', property: 'padding-bottom', value: 'var(--box-24)' },
{ selector: 'pb-32', property: 'padding-bottom', value: 'var(--box-32)' },
{ selector: 'pb-40', property: 'padding-bottom', value: 'var(--box-40)' },
{ selector: 'pb-48', property: 'padding-bottom', value: 'var(--box-48)' },

// .px-1 { padding-left: var(--box-1); padding-right: var(--box-1); }
// .px-2 { padding-left: var(--box-2); padding-right: var(--box-2); }
// .px-3 { padding-left: var(--box-3); padding-right: var(--box-3); }
// .px-4 { padding-left: var(--box-4); padding-right: var(--box-4); }
// .px-5 { padding-left: var(--box-5); padding-right: var(--box-5); }
// .px-6 { padding-left: var(--box-6); padding-right: var(--box-6); }
// .px-7 { padding-left: var(--box-7); padding-right: var(--box-7); }
// .px-8 { padding-left: var(--box-8); padding-right: var(--box-8); }
// .px-9 { padding-left: var(--box-9); padding-right: var(--box-9); }
// .px-10 { padding-left: var(--box-10); padding-right: var(--box-10); }
// .px-11 { padding-left: var(--box-11); padding-right: var(--box-11); }
// .px-11 { padding-left: var(--box-11); padding-right: var(--box-11); }
// .px-12 { padding-left: var(--box-12); padding-right: var(--box-12); }
// .px-12 { padding-left: var(--box-12); padding-right: var(--box-12); }
// .px-13 { padding-left: var(--box-13); padding-right: var(--box-13); }
// .px-13 { padding-left: var(--box-13); padding-right: var(--box-13); }
// .px-14 { padding-left: var(--box-14); padding-right: var(--box-14); }
// .px-14 { padding-left: var(--box-14); padding-right: var(--box-14); }
// .px-15 { padding-left: var(--box-15); padding-right: var(--box-15); }
// .px-15 { padding-left: var(--box-15); padding-right: var(--box-15); }
// .px-16 { padding-left: var(--box-16); padding-right: var(--box-16); }
// .px-24 { padding-left: var(--box-24); padding-right: var(--box-24); }
// .px-32 { padding-left: var(--box-32); padding-right: var(--box-32); }
// .px-40 { padding-left: var(--box-40); padding-right: var(--box-40); }
// .px-48 { padding-left: var(--box-48); padding-right: var(--box-48); }

// .py-1 { padding-top: var(--box-1); padding-bottom: var(--box-1); }
// .py-2 { padding-top: var(--box-2); padding-bottom: var(--box-2); }
// .py-3 { padding-top: var(--box-3); padding-bottom: var(--box-3); }
// .py-4 { padding-top: var(--box-4); padding-bottom: var(--box-4); }
// .py-5 { padding-top: var(--box-5); padding-bottom: var(--box-5); }
// .py-6 { padding-top: var(--box-6); padding-bottom: var(--box-6); }
// .py-7 { padding-top: var(--box-7); padding-bottom: var(--box-7); }
// .py-8 { padding-top: var(--box-8); padding-bottom: var(--box-8); }
// .py-9 { padding-top: var(--box-9); padding-bottom: var(--box-9); }
// .py-10 { padding-top: var(--box-10); padding-bottom: var(--box-10); }
// .py-11 { padding-top: var(--box-11); padding-bottom: var(--box-11); }
// .py-11 { padding-top: var(--box-11); padding-bottom: var(--box-11); }
// .py-12 { padding-top: var(--box-12); padding-bottom: var(--box-12); }
// .py-12 { padding-top: var(--box-12); padding-bottom: var(--box-12); }
// .py-13 { padding-top: var(--box-13); padding-bottom: var(--box-13); }
// .py-13 { padding-top: var(--box-13); padding-bottom: var(--box-13); }
// .py-14 { padding-top: var(--box-14); padding-bottom: var(--box-14); }
// .py-14 { padding-top: var(--box-14); padding-bottom: var(--box-14); }
// .py-15 { padding-top: var(--box-15); padding-bottom: var(--box-15); }
// .py-15 { padding-top: var(--box-15); padding-bottom: var(--box-15); }
// .py-16 { padding-top: var(--box-16); padding-bottom: var(--box-16); }
// .py-24 { padding-top: var(--box-24); padding-bottom: var(--box-24); }
// .py-32 { padding-top: var(--box-32); padding-bottom: var(--box-32); }
// .py-40 { padding-top: var(--box-40); padding-bottom: var(--box-40); }
// .py-48 { padding-top: var(--box-48); padding-bottom: var(--box-48); }

];
