import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const position: Array<FractureRuleType> = [
	{ selector: ".absolute", declarations: {position: "absolute"} },
	{ selector: ".fixed", declarations: {position: "fixed"} },
	{ selector: ".relative", declarations: {position: "relative"} },
	{ selector: ".static", declarations: {position: "static"} },
	{ selector: ".sticky", declarations: {position: "sticky"} },

	{ selector: ".z-0", declarations: {zIndex: "var(--z-index-0)"} as any },
	{ selector: ".z-10", declarations: {zIndex: "var(--z-index-10)"} as any },
	{ selector: ".z-20", declarations: {zIndex: "var(--z-index-20)"} as any },
	{ selector: ".z-30", declarations: {zIndex: "var(--z-index-30)"} as any },
	{ selector: ".z-40", declarations: {zIndex: "var(--z-index-40)"} as any },
	{ selector: ".z-50", declarations: {zIndex: "var(--z-index-50)"} as any },
	{ selector: ".z-60", declarations: {zIndex: "var(--z-index-60)"} as any },
	{ selector: ".z-70", declarations: {zIndex: "var(--z-index-70)"} as any },
	{ selector: ".z-80", declarations: {zIndex: "var(--z-index-80)"} as any },
	{ selector: ".z-90", declarations: {zIndex: "var(--z-index-90)"} as any },
	{ selector: ".z-100", declarations: {zIndex: "var(--z-index-100)"} as any },

	{ selector: ".bottom-0", declarations: {bottom: 0}, hasBreakpoints: true },
	{ selector: ".bottom-px", declarations: {bottom: "var(--box-px)"}, hasBreakpoints: true },
	{ selector: ".bottom-1", declarations: {bottom: "var(--box-1)"}, hasBreakpoints: true },
	{ selector: ".bottom-2", declarations: {bottom: "var(--box-2)"}, hasBreakpoints: true },
	{ selector: ".bottom-3", declarations: {bottom: "var(--box-3)"}, hasBreakpoints: true },
	{ selector: ".bottom-4", declarations: {bottom: "var(--box-4)"}, hasBreakpoints: true },
	{ selector: ".bottom-5", declarations: {bottom: "var(--box-5)"}, hasBreakpoints: true },
	{ selector: ".bottom-6", declarations: {bottom: "var(--box-6)"}, hasBreakpoints: true },
	{ selector: ".bottom-7", declarations: {bottom: "var(--box-7)"}, hasBreakpoints: true },
	{ selector: ".bottom-8", declarations: {bottom: "var(--box-8)"}, hasBreakpoints: true },
	{ selector: ".bottom-9", declarations: {bottom: "var(--box-9)"}, hasBreakpoints: true },
	{ selector: ".bottom-10", declarations: {bottom: "var(--box-10)"}, hasBreakpoints: true },
	{ selector: ".bottom-11", declarations: {bottom: "var(--box-11)"}, hasBreakpoints: true },
	{ selector: ".bottom-11", declarations: {bottom: "var(--box-11)"}, hasBreakpoints: true },
	{ selector: ".bottom-12", declarations: {bottom: "var(--box-12)"}, hasBreakpoints: true },
	{ selector: ".bottom-12", declarations: {bottom: "var(--box-12)"}, hasBreakpoints: true },
	{ selector: ".bottom-13", declarations: {bottom: "var(--box-13)"}, hasBreakpoints: true },
	{ selector: ".bottom-13", declarations: {bottom: "var(--box-13)"}, hasBreakpoints: true },
	{ selector: ".bottom-14", declarations: {bottom: "var(--box-14)"}, hasBreakpoints: true },
	{ selector: ".bottom-14", declarations: {bottom: "var(--box-14)"}, hasBreakpoints: true },
	{ selector: ".bottom-15", declarations: {bottom: "var(--box-15)"}, hasBreakpoints: true },
	{ selector: ".bottom-15", declarations: {bottom: "var(--box-15)"}, hasBreakpoints: true },
	{ selector: ".bottom-16", declarations: {bottom: "var(--box-16)"}, hasBreakpoints: true },
	{ selector: ".bottom-24", declarations: {bottom: "var(--box-24)"}, hasBreakpoints: true },
	{ selector: ".bottom-32", declarations: {bottom: "var(--box-32)"}, hasBreakpoints: true },
	{ selector: ".bottom-40", declarations: {bottom: "var(--box-40)"}, hasBreakpoints: true },
	{ selector: ".bottom-48", declarations: {bottom: "var(--box-48)"}, hasBreakpoints: true },

	{ selector: ".left-0", declarations: {left: 0}, hasBreakpoints: true },
	{ selector: ".left-px", declarations: {left: "var(--box-px)"}, hasBreakpoints: true },
	{ selector: ".left-1", declarations: {left: "var(--box-1)"}, hasBreakpoints: true },
	{ selector: ".left-2", declarations: {left: "var(--box-2)"}, hasBreakpoints: true },
	{ selector: ".left-3", declarations: {left: "var(--box-3)"}, hasBreakpoints: true },
	{ selector: ".left-4", declarations: {left: "var(--box-4)"}, hasBreakpoints: true },
	{ selector: ".left-5", declarations: {left: "var(--box-5)"}, hasBreakpoints: true },
	{ selector: ".left-6", declarations: {left: "var(--box-6)"}, hasBreakpoints: true },
	{ selector: ".left-7", declarations: {left: "var(--box-7)"}, hasBreakpoints: true },
	{ selector: ".left-8", declarations: {left: "var(--box-8)"}, hasBreakpoints: true },
	{ selector: ".left-9", declarations: {left: "var(--box-9)"}, hasBreakpoints: true },
	{ selector: ".left-10", declarations: {left: "var(--box-10)"}, hasBreakpoints: true },
	{ selector: ".left-11", declarations: {left: "var(--box-11)"}, hasBreakpoints: true },
	{ selector: ".left-11", declarations: {left: "var(--box-11)"}, hasBreakpoints: true },
	{ selector: ".left-12", declarations: {left: "var(--box-12)"}, hasBreakpoints: true },
	{ selector: ".left-12", declarations: {left: "var(--box-12)"}, hasBreakpoints: true },
	{ selector: ".left-13", declarations: {left: "var(--box-13)"}, hasBreakpoints: true },
	{ selector: ".left-13", declarations: {left: "var(--box-13)"}, hasBreakpoints: true },
	{ selector: ".left-14", declarations: {left: "var(--box-14)"}, hasBreakpoints: true },
	{ selector: ".left-14", declarations: {left: "var(--box-14)"}, hasBreakpoints: true },
	{ selector: ".left-15", declarations: {left: "var(--box-15)"}, hasBreakpoints: true },
	{ selector: ".left-15", declarations: {left: "var(--box-15)"}, hasBreakpoints: true },
	{ selector: ".left-16", declarations: {left: "var(--box-16)"}, hasBreakpoints: true },
	{ selector: ".left-24", declarations: {left: "var(--box-24)"}, hasBreakpoints: true },
	{ selector: ".left-32", declarations: {left: "var(--box-32)"}, hasBreakpoints: true },
	{ selector: ".left-40", declarations: {left: "var(--box-40)"}, hasBreakpoints: true },
	{ selector: ".left-48", declarations: {left: "var(--box-48)"}, hasBreakpoints: true },

	{ selector: ".right-0", declarations: {right: 0}, hasBreakpoints: true },
	{ selector: ".right-px", declarations: {right: "var(--box-px)"}, hasBreakpoints: true },
	{ selector: ".right-1", declarations: {right: "var(--box-1)"}, hasBreakpoints: true },
	{ selector: ".right-2", declarations: {right: "var(--box-2)"}, hasBreakpoints: true },
	{ selector: ".right-3", declarations: {right: "var(--box-3)"}, hasBreakpoints: true },
	{ selector: ".right-4", declarations: {right: "var(--box-4)"}, hasBreakpoints: true },
	{ selector: ".right-5", declarations: {right: "var(--box-5)"}, hasBreakpoints: true },
	{ selector: ".right-6", declarations: {right: "var(--box-6)"}, hasBreakpoints: true },
	{ selector: ".right-7", declarations: {right: "var(--box-7)"}, hasBreakpoints: true },
	{ selector: ".right-8", declarations: {right: "var(--box-8)"}, hasBreakpoints: true },
	{ selector: ".right-9", declarations: {right: "var(--box-9)"}, hasBreakpoints: true },
	{ selector: ".right-10", declarations: {right: "var(--box-10)"}, hasBreakpoints: true },
	{ selector: ".right-11", declarations: {right: "var(--box-11)"}, hasBreakpoints: true },
	{ selector: ".right-11", declarations: {right: "var(--box-11)"}, hasBreakpoints: true },
	{ selector: ".right-12", declarations: {right: "var(--box-12)"}, hasBreakpoints: true },
	{ selector: ".right-12", declarations: {right: "var(--box-12)"}, hasBreakpoints: true },
	{ selector: ".right-13", declarations: {right: "var(--box-13)"}, hasBreakpoints: true },
	{ selector: ".right-13", declarations: {right: "var(--box-13)"}, hasBreakpoints: true },
	{ selector: ".right-14", declarations: {right: "var(--box-14)"}, hasBreakpoints: true },
	{ selector: ".right-14", declarations: {right: "var(--box-14)"}, hasBreakpoints: true },
	{ selector: ".right-15", declarations: {right: "var(--box-15)"}, hasBreakpoints: true },
	{ selector: ".right-15", declarations: {right: "var(--box-15)"}, hasBreakpoints: true },
	{ selector: ".right-16", declarations: {right: "var(--box-16)"}, hasBreakpoints: true },
	{ selector: ".right-24", declarations: {right: "var(--box-24)"}, hasBreakpoints: true },
	{ selector: ".right-32", declarations: {right: "var(--box-32)"}, hasBreakpoints: true },
	{ selector: ".right-40", declarations: {right: "var(--box-40)"}, hasBreakpoints: true },
	{ selector: ".right-48", declarations: {right: "var(--box-48)"}, hasBreakpoints: true },

	{ selector: ".top-0", declarations: {top: 0}, hasBreakpoints: true },
	{ selector: ".top-px", declarations: {top: "var(--box-px)"}, hasBreakpoints: true },
	{ selector: ".top-1", declarations: {top: "var(--box-1)"}, hasBreakpoints: true },
	{ selector: ".top-2", declarations: {top: "var(--box-2)"}, hasBreakpoints: true },
	{ selector: ".top-3", declarations: {top: "var(--box-3)"}, hasBreakpoints: true },
	{ selector: ".top-4", declarations: {top: "var(--box-4)"}, hasBreakpoints: true },
	{ selector: ".top-5", declarations: {top: "var(--box-5)"}, hasBreakpoints: true },
	{ selector: ".top-6", declarations: {top: "var(--box-6)"}, hasBreakpoints: true },
	{ selector: ".top-7", declarations: {top: "var(--box-7)"}, hasBreakpoints: true },
	{ selector: ".top-8", declarations: {top: "var(--box-8)"}, hasBreakpoints: true },
	{ selector: ".top-9", declarations: {top: "var(--box-9)"}, hasBreakpoints: true },
	{ selector: ".top-10", declarations: {top: "var(--box-10)"}, hasBreakpoints: true },
	{ selector: ".top-11", declarations: {top: "var(--box-11)"}, hasBreakpoints: true },
	{ selector: ".top-11", declarations: {top: "var(--box-11)"}, hasBreakpoints: true },
	{ selector: ".top-12", declarations: {top: "var(--box-12)"}, hasBreakpoints: true },
	{ selector: ".top-12", declarations: {top: "var(--box-12)"}, hasBreakpoints: true },
	{ selector: ".top-13", declarations: {top: "var(--box-13)"}, hasBreakpoints: true },
	{ selector: ".top-13", declarations: {top: "var(--box-13)"}, hasBreakpoints: true },
	{ selector: ".top-14", declarations: {top: "var(--box-14)"}, hasBreakpoints: true },
	{ selector: ".top-14", declarations: {top: "var(--box-14)"}, hasBreakpoints: true },
	{ selector: ".top-15", declarations: {top: "var(--box-15)"}, hasBreakpoints: true },
	{ selector: ".top-15", declarations: {top: "var(--box-15)"}, hasBreakpoints: true },
	{ selector: ".top-16", declarations: {top: "var(--box-16)"}, hasBreakpoints: true },
	{ selector: ".top-24", declarations: {top: "var(--box-24)"}, hasBreakpoints: true },
	{ selector: ".top-32", declarations: {top: "var(--box-32)"}, hasBreakpoints: true },
	{ selector: ".top-40", declarations: {top: "var(--box-40)"}, hasBreakpoints: true },
	{ selector: ".top-48", declarations: {top: "var(--box-48)"}, hasBreakpoints: true },
];
