import type { FractureRuleType } from "../../types/css-rules";

export const position: Array<FractureRuleType> = [
  { selector: "absolute", declarations: { position: "absolute" }, description: 'Position is absolute.' },
  { selector: "fixed", declarations: { position: "fixed" }, description: 'Position is fixed.' },
  { selector: "relative", declarations: { position: "relative" }, description: 'Position is relative.' },
  { selector: "static", declarations: { position: "static" }, description: 'Position is static.' },
  { selector: "sticky", declarations: { position: "sticky" }, description: 'Position is sticky.' },

  { selector: "z-0", declarations: { zIndex: "var(--z-index-0)" }, description: 'Z-index is {0}.' },
  { selector: "z-10", declarations: { zIndex: "var(--z-index-10)" }, description: 'Z-index is {10}.' },
  { selector: "z-20", declarations: { zIndex: "var(--z-index-20)" }, description: 'Z-index is {20}.' },
  { selector: "z-30", declarations: { zIndex: "var(--z-index-30)" }, description: 'Z-index is {30}.' },
  { selector: "z-40", declarations: { zIndex: "var(--z-index-40)" }, description: 'Z-index is {40}.' },
  { selector: "z-50", declarations: { zIndex: "var(--z-index-50)" }, description: 'Z-index is {50}.' },
  { selector: "z-60", declarations: { zIndex: "var(--z-index-60)" }, description: 'Z-index is {60}.' },
  { selector: "z-70", declarations: { zIndex: "var(--z-index-70)" }, description: 'Z-index is {70}.' },
  { selector: "z-80", declarations: { zIndex: "var(--z-index-80)" }, description: 'Z-index is {80}.' },
  { selector: "z-90", declarations: { zIndex: "var(--z-index-90)" }, description: 'Z-index is {90}.' },
  { selector: "z-100", declarations: { zIndex: "var(--z-index-100)" }, description: 'Z-index is {100}.' },

  { selector: "bottom-0", declarations: { bottom: 0 }, description: 'Space from bottom is 0.' },
  { selector: "bottom-px", declarations: { bottom: "var(--box-px)" }, description: 'Space from bottom is {1}px.' },
  { selector: "bottom-1", declarations: { bottom: "var(--box-1)" }, description: 'Space from bottom is {2}px.' },
  { selector: "bottom-2", declarations: { bottom: "var(--box-2)" }, description: 'Space from bottom is {4}px.' },
  { selector: "bottom-3", declarations: { bottom: "var(--box-3)" }, description: 'Space from bottom is {6}px.' },
  { selector: "bottom-4", declarations: { bottom: "var(--box-4)" }, description: 'Space from bottom is {8}px.' },
  { selector: "bottom-5", declarations: { bottom: "var(--box-5)" }, description: 'Space from bottom is {10}px.' },
  { selector: "bottom-6", declarations: { bottom: "var(--box-6)" }, description: 'Space from bottom is {12}px.' },
  { selector: "bottom-7", declarations: { bottom: "var(--box-7)" }, description: 'Space from bottom is {14}px.' },
  { selector: "bottom-8", declarations: { bottom: "var(--box-8)" }, description: 'Space from bottom is {16}px.' },
  { selector: "bottom-9", declarations: { bottom: "var(--box-9)" }, description: 'Space from bottom is {18}px.' },
  { selector: "bottom-10", declarations: { bottom: "var(--box-10)" }, description: 'Space from bottom is {20}px.' },
  { selector: "bottom-11", declarations: { bottom: "var(--box-11)" }, description: 'Space from bottom is {22}px.' },
  { selector: "bottom-12", declarations: { bottom: "var(--box-12)" }, description: 'Space from bottom is {24}px.' },
  { selector: "bottom-13", declarations: { bottom: "var(--box-13)" }, description: 'Space from bottom is {26}px.' },
  { selector: "bottom-14", declarations: { bottom: "var(--box-14)" }, description: 'Space from bottom is {28}px.' },
  { selector: "bottom-15", declarations: { bottom: "var(--box-15)" }, description: 'Space from bottom is {30}px.' },
  { selector: "bottom-16", declarations: { bottom: "var(--box-16)" }, description: 'Space from bottom is {32}px.' },
  { selector: "bottom-24", declarations: { bottom: "var(--box-24)" }, description: 'Space from bottom is {48}px.' },
  { selector: "bottom-32", declarations: { bottom: "var(--box-32)" }, description: 'Space from bottom is {64}px.' },
  { selector: "bottom-40", declarations: { bottom: "var(--box-40)" }, description: 'Space from bottom is {80}px.' },
  { selector: "bottom-48", declarations: { bottom: "var(--box-48)" }, description: 'Space from bottom is {96}px.' },

  { selector: "left-0", declarations: { left: 0 }, description: 'Space from left is 0.' },
  { selector: "left-px", declarations: { left: "var(--box-px)" }, description: 'Space from left is {1}px.' },
  { selector: "left-1", declarations: { left: "var(--box-1)" }, description: 'Space from left is {2}px.' },
  { selector: "left-2", declarations: { left: "var(--box-2)" }, description: 'Space from left is {4}px.' },
  { selector: "left-3", declarations: { left: "var(--box-3)" }, description: 'Space from left is {6}px.' },
  { selector: "left-4", declarations: { left: "var(--box-4)" }, description: 'Space from left is {8}px.' },
  { selector: "left-5", declarations: { left: "var(--box-5)" }, description: 'Space from left is {10}px.' },
  { selector: "left-6", declarations: { left: "var(--box-6)" }, description: 'Space from left is {12}px.' },
  { selector: "left-7", declarations: { left: "var(--box-7)" }, description: 'Space from left is {14}px.' },
  { selector: "left-8", declarations: { left: "var(--box-8)" }, description: 'Space from left is {16}px.' },
  { selector: "left-9", declarations: { left: "var(--box-9)" }, description: 'Space from left is {18}px.' },
  { selector: "left-10", declarations: { left: "var(--box-10)" }, description: 'Space from left is {20}px.' },
  { selector: "left-11", declarations: { left: "var(--box-11)" }, description: 'Space from left is {22}px.' },
  { selector: "left-12", declarations: { left: "var(--box-12)" }, description: 'Space from left is {24}px.' },
  { selector: "left-13", declarations: { left: "var(--box-13)" }, description: 'Space from left is {26}px.' },
  { selector: "left-14", declarations: { left: "var(--box-14)" }, description: 'Space from left is {28}px.' },
  { selector: "left-15", declarations: { left: "var(--box-15)" }, description: 'Space from left is {30}px.' },
  { selector: "left-16", declarations: { left: "var(--box-16)" }, description: 'Space from left is {32}px.' },
  { selector: "left-24", declarations: { left: "var(--box-24)" }, description: 'Space from left is {48}px.' },
  { selector: "left-32", declarations: { left: "var(--box-32)" }, description: 'Space from left is {64}px.' },
  { selector: "left-40", declarations: { left: "var(--box-40)" }, description: 'Space from left is {80}px.' },
  { selector: "left-48", declarations: { left: "var(--box-48)" }, description: 'Space from left is {96}px.' },

  { selector: "right-0", declarations: { right: 0 }, description: 'Space from right is 0.' },
  { selector: "right-px", declarations: { right: "var(--box-px)" }, description: 'Space from right is {1}px.' },
  { selector: "right-1", declarations: { right: "var(--box-1)" }, description: 'Space from right is {2}px.' },
  { selector: "right-2", declarations: { right: "var(--box-2)" }, description: 'Space from right is {4}px.' },
  { selector: "right-3", declarations: { right: "var(--box-3)" }, description: 'Space from right is {6}px.' },
  { selector: "right-4", declarations: { right: "var(--box-4)" }, description: 'Space from right is {8}px.' },
  { selector: "right-5", declarations: { right: "var(--box-5)" }, description: 'Space from right is {10}px.' },
  { selector: "right-6", declarations: { right: "var(--box-6)" }, description: 'Space from right is {12}px.' },
  { selector: "right-7", declarations: { right: "var(--box-7)" }, description: 'Space from right is {14}px.' },
  { selector: "right-8", declarations: { right: "var(--box-8)" }, description: 'Space from right is {16}px.' },
  { selector: "right-9", declarations: { right: "var(--box-9)" }, description: 'Space from right is {18}px.' },
  { selector: "right-10", declarations: { right: "var(--box-10)" }, description: 'Space from right is {20}px.' },
  { selector: "right-11", declarations: { right: "var(--box-11)" }, description: 'Space from right is {22}px.' },
  { selector: "right-12", declarations: { right: "var(--box-12)" }, description: 'Space from right is {24}px.' },
  { selector: "right-13", declarations: { right: "var(--box-13)" }, description: 'Space from right is {26}px.' },
  { selector: "right-14", declarations: { right: "var(--box-14)" }, description: 'Space from right is {28}px.' },
  { selector: "right-15", declarations: { right: "var(--box-15)" }, description: 'Space from right is {30}px.' },
  { selector: "right-16", declarations: { right: "var(--box-16)" }, description: 'Space from right is {32}px.' },
  { selector: "right-24", declarations: { right: "var(--box-24)" }, description: 'Space from right is {48}px.' },
  { selector: "right-32", declarations: { right: "var(--box-32)" }, description: 'Space from right is {64}px.' },
  { selector: "right-40", declarations: { right: "var(--box-40)" }, description: 'Space from right is {80}px.' },
  { selector: "right-48", declarations: { right: "var(--box-48)" }, description: 'Space from right is {96}px.' },

  { selector: "top-0", declarations: { top: 0 }, description: 'Space from top is 0.' },
  { selector: "top-px", declarations: { top: "var(--box-px)" }, description: 'Space from top is {1}px.' },
  { selector: "top-1", declarations: { top: "var(--box-1)" }, description: 'Space from top is {2}px.' },
  { selector: "top-2", declarations: { top: "var(--box-2)" }, description: 'Space from top is {4}px.' },
  { selector: "top-3", declarations: { top: "var(--box-3)" }, description: 'Space from top is {6}px.' },
  { selector: "top-4", declarations: { top: "var(--box-4)" }, description: 'Space from top is {8}px.' },
  { selector: "top-5", declarations: { top: "var(--box-5)" }, description: 'Space from top is {10}px.' },
  { selector: "top-6", declarations: { top: "var(--box-6)" }, description: 'Space from top is {12}px.' },
  { selector: "top-7", declarations: { top: "var(--box-7)" }, description: 'Space from top is {14}px.' },
  { selector: "top-8", declarations: { top: "var(--box-8)" }, description: 'Space from top is {16}px.' },
  { selector: "top-9", declarations: { top: "var(--box-9)" }, description: 'Space from top is {18}px.' },
  { selector: "top-10", declarations: { top: "var(--box-10)" }, description: 'Space from top is {20}px.' },
  { selector: "top-11", declarations: { top: "var(--box-11)" }, description: 'Space from top is {22}px.' },
  { selector: "top-12", declarations: { top: "var(--box-12)" }, description: 'Space from top is {24}px.' },
  { selector: "top-13", declarations: { top: "var(--box-13)" }, description: 'Space from top is {26}px.' },
  { selector: "top-14", declarations: { top: "var(--box-14)" }, description: 'Space from top is {28}px.' },
  { selector: "top-15", declarations: { top: "var(--box-15)" }, description: 'Space from top is {30}px.' },
  { selector: "top-16", declarations: { top: "var(--box-16)" }, description: 'Space from top is {32}px.' },
  { selector: "top-24", declarations: { top: "var(--box-24)" }, description: 'Space from top is {48}px.' },
  { selector: "top-32", declarations: { top: "var(--box-32)" }, description: 'Space from top is {64}px.' },
  { selector: "top-40", declarations: { top: "var(--box-40)" }, description: 'Space from top is {80}px.' },
  { selector: "top-48", declarations: { top: "var(--box-48)" }, description: 'Space from top is {96}px.' },
];
