import type { FractureRuleType } from "../../types/css-rules";

// prettier-ignore
export const position: Array<FractureRuleType> = [
	{ selector: "absolute", property: "position", value: "absolute" },
	{ selector: "fixed", property: "position", value: "fixed" },
	{ selector: "relative", property: "position", value: "relative" },
	{ selector: "static", property: "position", value: "static" },
	{ selector: "sticky", property: "position", value: "sticky" },

	{ selector: "z-0", property: "z-index", value: "var(--z-index-0)" },
	{ selector: "z-10", property: "z-index", value: "var(--z-index-10)" },
	{ selector: "z-20", property: "z-index", value: "var(--z-index-20)" },
	{ selector: "z-30", property: "z-index", value: "var(--z-index-30)" },
	{ selector: "z-40", property: "z-index", value: "var(--z-index-40)" },
	{ selector: "z-50", property: "z-index", value: "var(--z-index-50)" },
	{ selector: "z-60", property: "z-index", value: "var(--z-index-60)" },
	{ selector: "z-70", property: "z-index", value: "var(--z-index-70)" },
	{ selector: "z-80", property: "z-index", value: "var(--z-index-80)" },
	{ selector: "z-90", property: "z-index", value: "var(--z-index-90)" },
	{ selector: "z-100", property: "z-index", value: "var(--z-index-100)" },

	{ selector: "bottom-0", property: "bottom", value: "0", hasBreakpoints: true },
	{ selector: "bottom-px", property: "bottom", value: "var(--box-px)", hasBreakpoints: true },
	{ selector: "bottom-1", property: "bottom", value: "var(--box-1)", hasBreakpoints: true },
	{ selector: "bottom-2", property: "bottom", value: "var(--box-2)", hasBreakpoints: true },
	{ selector: "bottom-3", property: "bottom", value: "var(--box-3)", hasBreakpoints: true },
	{ selector: "bottom-4", property: "bottom", value: "var(--box-4)", hasBreakpoints: true },
	{ selector: "bottom-5", property: "bottom", value: "var(--box-5)", hasBreakpoints: true },
	{ selector: "bottom-6", property: "bottom", value: "var(--box-6)", hasBreakpoints: true },
	{ selector: "bottom-7", property: "bottom", value: "var(--box-7)", hasBreakpoints: true },
	{ selector: "bottom-8", property: "bottom", value: "var(--box-8)", hasBreakpoints: true },
	{ selector: "bottom-9", property: "bottom", value: "var(--box-9)", hasBreakpoints: true },
	{ selector: "bottom-10", property: "bottom", value: "var(--box-10)", hasBreakpoints: true },
	{ selector: "bottom-11", property: "bottom", value: "var(--box-11)", hasBreakpoints: true },
	{ selector: "bottom-11", property: "bottom", value: "var(--box-11)", hasBreakpoints: true },
	{ selector: "bottom-12", property: "bottom", value: "var(--box-12)", hasBreakpoints: true },
	{ selector: "bottom-12", property: "bottom", value: "var(--box-12)", hasBreakpoints: true },
	{ selector: "bottom-13", property: "bottom", value: "var(--box-13)", hasBreakpoints: true },
	{ selector: "bottom-13", property: "bottom", value: "var(--box-13)", hasBreakpoints: true },
	{ selector: "bottom-14", property: "bottom", value: "var(--box-14)", hasBreakpoints: true },
	{ selector: "bottom-14", property: "bottom", value: "var(--box-14)", hasBreakpoints: true },
	{ selector: "bottom-15", property: "bottom", value: "var(--box-15)", hasBreakpoints: true },
	{ selector: "bottom-15", property: "bottom", value: "var(--box-15)", hasBreakpoints: true },
	{ selector: "bottom-16", property: "bottom", value: "var(--box-16)", hasBreakpoints: true },
	{ selector: "bottom-24", property: "bottom", value: "var(--box-24)", hasBreakpoints: true },
	{ selector: "bottom-32", property: "bottom", value: "var(--box-32)", hasBreakpoints: true },
	{ selector: "bottom-40", property: "bottom", value: "var(--box-40)", hasBreakpoints: true },
	{ selector: "bottom-48", property: "bottom", value: "var(--box-48)", hasBreakpoints: true },

	{ selector: "left-0", property: "left", value: "0", hasBreakpoints: true },
	{ selector: "left-px", property: "left", value: "var(--box-px)", hasBreakpoints: true },
	{ selector: "left-1", property: "left", value: "var(--box-1)", hasBreakpoints: true },
	{ selector: "left-2", property: "left", value: "var(--box-2)", hasBreakpoints: true },
	{ selector: "left-3", property: "left", value: "var(--box-3)", hasBreakpoints: true },
	{ selector: "left-4", property: "left", value: "var(--box-4)", hasBreakpoints: true },
	{ selector: "left-5", property: "left", value: "var(--box-5)", hasBreakpoints: true },
	{ selector: "left-6", property: "left", value: "var(--box-6)", hasBreakpoints: true },
	{ selector: "left-7", property: "left", value: "var(--box-7)", hasBreakpoints: true },
	{ selector: "left-8", property: "left", value: "var(--box-8)", hasBreakpoints: true },
	{ selector: "left-9", property: "left", value: "var(--box-9)", hasBreakpoints: true },
	{ selector: "left-10", property: "left", value: "var(--box-10)", hasBreakpoints: true },
	{ selector: "left-11", property: "left", value: "var(--box-11)", hasBreakpoints: true },
	{ selector: "left-11", property: "left", value: "var(--box-11)", hasBreakpoints: true },
	{ selector: "left-12", property: "left", value: "var(--box-12)", hasBreakpoints: true },
	{ selector: "left-12", property: "left", value: "var(--box-12)", hasBreakpoints: true },
	{ selector: "left-13", property: "left", value: "var(--box-13)", hasBreakpoints: true },
	{ selector: "left-13", property: "left", value: "var(--box-13)", hasBreakpoints: true },
	{ selector: "left-14", property: "left", value: "var(--box-14)", hasBreakpoints: true },
	{ selector: "left-14", property: "left", value: "var(--box-14)", hasBreakpoints: true },
	{ selector: "left-15", property: "left", value: "var(--box-15)", hasBreakpoints: true },
	{ selector: "left-15", property: "left", value: "var(--box-15)", hasBreakpoints: true },
	{ selector: "left-16", property: "left", value: "var(--box-16)", hasBreakpoints: true },
	{ selector: "left-24", property: "left", value: "var(--box-24)", hasBreakpoints: true },
	{ selector: "left-32", property: "left", value: "var(--box-32)", hasBreakpoints: true },
	{ selector: "left-40", property: "left", value: "var(--box-40)", hasBreakpoints: true },
	{ selector: "left-48", property: "left", value: "var(--box-48)", hasBreakpoints: true },

	{ selector: "right-0", property: "right", value: "0", hasBreakpoints: true },
	{ selector: "right-px", property: "right", value: "var(--box-px)", hasBreakpoints: true },
	{ selector: "right-1", property: "right", value: "var(--box-1)", hasBreakpoints: true },
	{ selector: "right-2", property: "right", value: "var(--box-2)", hasBreakpoints: true },
	{ selector: "right-3", property: "right", value: "var(--box-3)", hasBreakpoints: true },
	{ selector: "right-4", property: "right", value: "var(--box-4)", hasBreakpoints: true },
	{ selector: "right-5", property: "right", value: "var(--box-5)", hasBreakpoints: true },
	{ selector: "right-6", property: "right", value: "var(--box-6)", hasBreakpoints: true },
	{ selector: "right-7", property: "right", value: "var(--box-7)", hasBreakpoints: true },
	{ selector: "right-8", property: "right", value: "var(--box-8)", hasBreakpoints: true },
	{ selector: "right-9", property: "right", value: "var(--box-9)", hasBreakpoints: true },
	{ selector: "right-10", property: "right", value: "var(--box-10)", hasBreakpoints: true },
	{ selector: "right-11", property: "right", value: "var(--box-11)", hasBreakpoints: true },
	{ selector: "right-11", property: "right", value: "var(--box-11)", hasBreakpoints: true },
	{ selector: "right-12", property: "right", value: "var(--box-12)", hasBreakpoints: true },
	{ selector: "right-12", property: "right", value: "var(--box-12)", hasBreakpoints: true },
	{ selector: "right-13", property: "right", value: "var(--box-13)", hasBreakpoints: true },
	{ selector: "right-13", property: "right", value: "var(--box-13)", hasBreakpoints: true },
	{ selector: "right-14", property: "right", value: "var(--box-14)", hasBreakpoints: true },
	{ selector: "right-14", property: "right", value: "var(--box-14)", hasBreakpoints: true },
	{ selector: "right-15", property: "right", value: "var(--box-15)", hasBreakpoints: true },
	{ selector: "right-15", property: "right", value: "var(--box-15)", hasBreakpoints: true },
	{ selector: "right-16", property: "right", value: "var(--box-16)", hasBreakpoints: true },
	{ selector: "right-24", property: "right", value: "var(--box-24)", hasBreakpoints: true },
	{ selector: "right-32", property: "right", value: "var(--box-32)", hasBreakpoints: true },
	{ selector: "right-40", property: "right", value: "var(--box-40)", hasBreakpoints: true },
	{ selector: "right-48", property: "right", value: "var(--box-48)", hasBreakpoints: true },

	{ selector: "top-0", property: "top", value: "0", hasBreakpoints: true },
	{ selector: "top-px", property: "top", value: "var(--box-px)", hasBreakpoints: true },
	{ selector: "top-1", property: "top", value: "var(--box-1)", hasBreakpoints: true },
	{ selector: "top-2", property: "top", value: "var(--box-2)", hasBreakpoints: true },
	{ selector: "top-3", property: "top", value: "var(--box-3)", hasBreakpoints: true },
	{ selector: "top-4", property: "top", value: "var(--box-4)", hasBreakpoints: true },
	{ selector: "top-5", property: "top", value: "var(--box-5)", hasBreakpoints: true },
	{ selector: "top-6", property: "top", value: "var(--box-6)", hasBreakpoints: true },
	{ selector: "top-7", property: "top", value: "var(--box-7)", hasBreakpoints: true },
	{ selector: "top-8", property: "top", value: "var(--box-8)", hasBreakpoints: true },
	{ selector: "top-9", property: "top", value: "var(--box-9)", hasBreakpoints: true },
	{ selector: "top-10", property: "top", value: "var(--box-10)", hasBreakpoints: true },
	{ selector: "top-11", property: "top", value: "var(--box-11)", hasBreakpoints: true },
	{ selector: "top-11", property: "top", value: "var(--box-11)", hasBreakpoints: true },
	{ selector: "top-12", property: "top", value: "var(--box-12)", hasBreakpoints: true },
	{ selector: "top-12", property: "top", value: "var(--box-12)", hasBreakpoints: true },
	{ selector: "top-13", property: "top", value: "var(--box-13)", hasBreakpoints: true },
	{ selector: "top-13", property: "top", value: "var(--box-13)", hasBreakpoints: true },
	{ selector: "top-14", property: "top", value: "var(--box-14)", hasBreakpoints: true },
	{ selector: "top-14", property: "top", value: "var(--box-14)", hasBreakpoints: true },
	{ selector: "top-15", property: "top", value: "var(--box-15)", hasBreakpoints: true },
	{ selector: "top-15", property: "top", value: "var(--box-15)", hasBreakpoints: true },
	{ selector: "top-16", property: "top", value: "var(--box-16)", hasBreakpoints: true },
	{ selector: "top-24", property: "top", value: "var(--box-24)", hasBreakpoints: true },
	{ selector: "top-32", property: "top", value: "var(--box-32)", hasBreakpoints: true },
	{ selector: "top-40", property: "top", value: "var(--box-40)", hasBreakpoints: true },
	{ selector: "top-48", property: "top", value: "var(--box-48)", hasBreakpoints: true },
];
