export const config: string = `:root {
	--box-px: unset;
	--box-1: unset;
	--box-2: unset;
	--box-3: unset;
	--box-4: unset;
	--box-5: unset;
	--box-6: unset;
	--box-7: unset;
	--box-8: unset;
	--box-9: unset;
	--box-10: unset;
	--box-11: unset;
	--box-12: unset;
	--box-13: unset;
	--box-14: unset;
	--box-15: unset;
	--box-16: unset;
	--box-24: unset;
	--box-32: unset;
	--box-40: unset;
	--box-48: unset;

	--font-size-h0: unset;
	--font-size-h1: unset;
	--font-size-h2: unset;
	--font-size-h3: unset;
	--font-size-h4: unset;
	--font-size-h5: unset;
	--font-size-h6: unset;
	--font-size-p: unset;
	--font-size-small: unset;
	--font-size-tiny: unset;
	--font-size-micro: unset;

	--line-height-h1: unset;
	--line-height-h2: unset;
	--line-height-h3: unset;
	--line-height-h4: unset;
	--line-height-h5: unset;
	--line-height-h6: unset;
	--line-height-p: unset;
	--line-height-small: unset;
	--line-height-tiny: unset;
	--line-height-micro: unset;

	--font-family-sans: unset;
	--font-family-serif: unset;
	--font-family-mono: unset;

  --font-weight-thin: unset;
  --font-weight-extra-light: unset;
  --font-weight-light: unset;
  --font-weight-normal: unset;
  --font-weight-medium: unset;
  --font-weight-semi-bold: unset;
  --font-weight-bold: unset;
  --font-weight-extra-bold: unset;
  --font-weight-black: unset;

	--z-index-0: 0;
	--z-index-1: unset;
	--z-index-2: unset;
	--z-index-3: unset;
	--z-index-4: unset;
	--z-index-5: unset;
	--z-index-6: unset;
	--z-index-7: unset;
	--z-index-8: unset;
	--z-index-9: unset;
	--z-index-10: unset;
}`
